export type QuestionDifficulty = "Foundation" | "Standard" | "Challenge";

export type QuizQuestion = {
  id: string;
  chapter: string;
  difficulty: QuestionDifficulty;
  stem: string;
  options: [string, string, string, string];
  answer: number;
  explanation: string;
};

export const quizQuestions: QuizQuestion[] = [
  {
    id: "virus-envelope-entry",
    chapter: "Acellular Life",
    difficulty: "Standard",
    stem: "The host-derived envelope is removed from an otherwise intact influenza virion. Which function should decline most sharply?",
    options: ["Viral RNA synthesis", "Capsomere assembly", "Receptor-mediated entry", "Copying of host DNA"],
    answer: 2,
    explanation: "Influenza envelope glycoproteins attach to host receptors and mediate membrane entry. Removing the envelope damages this earliest host-recognition step.",
  },
  {
    id: "positive-rna",
    chapter: "Acellular Life",
    difficulty: "Foundation",
    stem: "Why can the genome of a positive-sense RNA virus begin directing protein synthesis soon after uncoating?",
    options: ["It acts directly as mRNA", "It contains host ribosomes", "It first becomes a prion", "It is always double-stranded"],
    answer: 0,
    explanation: "Positive-sense RNA has the same readable orientation as mRNA, so host ribosomes can translate it directly.",
  },
  {
    id: "negative-rna-polymerase",
    chapter: "Acellular Life",
    difficulty: "Challenge",
    stem: "A negative-sense RNA virus enters a cell without a functional RNA-dependent RNA polymerase. What is the most immediate consequence?",
    options: ["Its capsid cannot attach", "Its DNA cannot integrate", "Its envelope becomes bacterial", "Its genome cannot produce readable mRNA"],
    answer: 3,
    explanation: "Negative-sense RNA is complementary to mRNA. A viral polymerase must first make a positive-sense RNA that host ribosomes can read.",
  },
  {
    id: "provirus",
    chapter: "Acellular Life",
    difficulty: "Standard",
    stem: "Which description identifies a provirus rather than a free virion?",
    options: ["Protein-only infectious agent", "Circular plant RNA without capsid", "Viral DNA integrated into host DNA", "Complete particle outside a host cell"],
    answer: 2,
    explanation: "A provirus is a viral DNA stage integrated into the host genome. A virion is the complete extracellular infectious particle.",
  },
  {
    id: "sodium-pump",
    chapter: "Cell Structure & Function",
    difficulty: "Challenge",
    stem: "A toxin blocks all sodium–potassium pumps in an animal cell. Which change should develop gradually?",
    options: ["Loss of sodium and potassium gradients", "Immediate destruction of nuclear DNA", "Permanent closure of every ion channel", "Conversion of lysosomes into ribosomes"],
    answer: 0,
    explanation: "The pump continually maintains unequal sodium and potassium distributions. Existing gradients persist briefly but dissipate as ions continue moving through channels.",
  },
  {
    id: "lysosome-ph",
    chapter: "Cell Structure & Function",
    difficulty: "Standard",
    stem: "Why does rupture of a few lysosomes not normally digest the entire cytoplasm immediately?",
    options: ["Their enzymes contain no peptide bonds", "The enzymes can digest only lipids", "Cytoplasm has no water", "Many lysosomal enzymes work best at acidic pH"],
    answer: 3,
    explanation: "Lysosomal hydrolases are optimized for an acidic compartment. The near-neutral cytosol reduces their activity, although extensive rupture can still injure the cell.",
  },
  {
    id: "cristae",
    chapter: "Cell Structure & Function",
    difficulty: "Foundation",
    stem: "An increase in mitochondrial cristae most directly provides more surface for:",
    options: ["DNA replication in the nucleus", "Glycolysis in the cytosol", "Electron transport and ATP synthase", "Protein digestion in lysosomes"],
    answer: 2,
    explanation: "The inner mitochondrial membrane contains electron-transport proteins and ATP synthase. Cristae increase its usable surface area.",
  },
  {
    id: "osmosis-cell",
    chapter: "Cell Structure & Function",
    difficulty: "Standard",
    stem: "A red blood cell is placed in a solution with a lower water potential than its cytoplasm. What follows first?",
    options: ["Water enters and the cell lyses", "ATP production stops instantly", "Solute leaves by osmosis", "Water leaves and the cell shrinks"],
    answer: 3,
    explanation: "Water moves from higher to lower water potential across the membrane, so it leaves the cell and the cell becomes crenated.",
  },
  {
    id: "competitive-inhibition",
    chapter: "Enzymes",
    difficulty: "Challenge",
    stem: "A competitive inhibitor is added to an enzyme-controlled reaction. Which kinetic pattern is expected?",
    options: ["Lower apparent Km and lower Vmax", "Unchanged Km with lower Vmax", "Higher apparent Km with unchanged Vmax", "Both Km and Vmax become zero"],
    answer: 2,
    explanation: "More substrate is needed to reach half-maximal rate, so apparent Km rises. Sufficient substrate can outcompete the inhibitor, leaving Vmax unchanged.",
  },
  {
    id: "noncompetitive-inhibition",
    chapter: "Enzymes",
    difficulty: "Challenge",
    stem: "Why can adding excess substrate fail to restore the original maximum rate in non-competitive inhibition?",
    options: ["The inhibitor permanently removes all substrate", "The active site becomes another substrate", "The substrate stops colliding with enzymes", "The inhibitor reduces the amount of functional enzyme"],
    answer: 3,
    explanation: "A pure non-competitive inhibitor reduces functional catalytic capacity through a separate binding site. More substrate cannot recover the lost Vmax.",
  },
  {
    id: "temperature-enzyme",
    chapter: "Enzymes",
    difficulty: "Standard",
    stem: "An enzyme reaction slows sharply above its optimum temperature even though molecular collisions are more frequent. The best explanation is:",
    options: ["Substrate gains no kinetic energy", "Activation energy increases because of more collisions", "All products become enzymes", "The enzyme's active-site shape is disrupted"],
    answer: 3,
    explanation: "High temperature disrupts bonds maintaining tertiary structure. Loss of active-site complementarity outweighs the collision-rate increase.",
  },
  {
    id: "ph-enzyme",
    chapter: "Enzymes",
    difficulty: "Standard",
    stem: "A change in pH reduces enzyme activity without breaking peptide bonds. Which change most directly explains the result?",
    options: ["Altered ionization of active-site groups", "Removal of every carbon atom", "Conversion of protein into DNA", "Loss of all water from the reaction"],
    answer: 0,
    explanation: "pH changes the charge of amino-acid side chains, disturbing substrate binding or catalysis even when the primary structure remains intact.",
  },
  {
    id: "oxygen-acceptor",
    chapter: "Bioenergetics",
    difficulty: "Foundation",
    stem: "In aerobic respiration, oxygen is required most directly because it:",
    options: ["Splits glucose during glycolysis", "Carries ATP into the nucleus", "Accepts electrons at the end of the transport chain", "Converts pyruvate into glucose"],
    answer: 2,
    explanation: "Oxygen accepts electrons and protons at the end of the electron-transport chain, allowing electron flow and oxidative phosphorylation to continue.",
  },
  {
    id: "glycolysis-location",
    chapter: "Bioenergetics",
    difficulty: "Foundation",
    stem: "A cell temporarily loses functional mitochondria but retains an intact cytosol. Which process can still produce a small amount of ATP?",
    options: ["Krebs cycle", "Oxidative phosphorylation", "Glycolysis", "Link reaction"],
    answer: 2,
    explanation: "Glycolysis occurs in the cytosol and produces ATP by substrate-level phosphorylation without requiring mitochondria.",
  },
  {
    id: "proton-gradient",
    chapter: "Bioenergetics",
    difficulty: "Standard",
    stem: "The inner mitochondrial membrane suddenly becomes freely permeable to protons. Which event is affected most directly?",
    options: ["ATP synthesis by chemiosmosis", "Glucose entry into glycolysis", "DNA transcription in the nucleus", "Peptide-bond formation on ribosomes"],
    answer: 0,
    explanation: "ATP synthase depends on proton flow down an electrochemical gradient. A proton-permeable membrane collapses that gradient.",
  },
  {
    id: "uncoupler",
    chapter: "Bioenergetics",
    difficulty: "Challenge",
    stem: "A mitochondrial uncoupler increases proton leakage. Which combination is most likely?",
    options: ["Less oxygen use and more ATP", "More ATP with no heat production", "No electron transport and more ATP", "More oxygen use but less ATP"],
    answer: 3,
    explanation: "Electron transport may accelerate while the gradient is dissipated as heat. Oxygen consumption can rise even though ATP production falls.",
  },
  {
    id: "ventricle-wall",
    chapter: "Circulation",
    difficulty: "Standard",
    stem: "Why is the left ventricular myocardium thicker than the right ventricular myocardium?",
    options: ["It fills from the venae cavae", "It receives blood from the pulmonary artery", "It opens the tricuspid valve", "It pumps against greater systemic resistance"],
    answer: 3,
    explanation: "The systemic circuit presents greater resistance and requires higher pressure than the short pulmonary circuit.",
  },
  {
    id: "av-valve",
    chapter: "Circulation",
    difficulty: "Standard",
    stem: "At which pressure relationship should an atrioventricular valve open?",
    options: ["Ventricular pressure exceeds arterial pressure", "Atrial pressure exceeds ventricular pressure", "Arterial pressure equals zero", "Ventricular pressure exceeds atrial pressure"],
    answer: 1,
    explanation: "AV valves open when atrial pressure becomes greater than ventricular pressure, allowing ventricular filling.",
  },
  {
    id: "sa-node",
    chapter: "Circulation",
    difficulty: "Foundation",
    stem: "Damage to the sinoatrial node most directly disrupts:",
    options: ["Exchange across capillaries", "Oxygen binding to haemoglobin", "Initiation of the normal heartbeat", "Closing of venous valves in the legs"],
    answer: 2,
    explanation: "The sinoatrial node normally acts as the heart's pacemaker and initiates each wave of cardiac excitation.",
  },
  {
    id: "capillary-wall",
    chapter: "Circulation",
    difficulty: "Standard",
    stem: "The one-cell-thick capillary wall mainly improves exchange by:",
    options: ["Increasing diffusion distance", "Reducing diffusion distance", "Preventing all pressure loss", "Producing red blood cells"],
    answer: 1,
    explanation: "A thin wall shortens the diffusion pathway between blood and tissue fluid, increasing exchange efficiency.",
  },
  {
    id: "depolarization",
    chapter: "Coordination & Control",
    difficulty: "Standard",
    stem: "Which ion movement causes the rapid depolarization phase of a typical neuronal action potential?",
    options: ["Potassium enters", "Sodium enters", "Chloride leaves", "Calcium leaves the axon"],
    answer: 1,
    explanation: "Voltage-gated sodium channels open, allowing sodium ions to enter down their electrochemical gradient.",
  },
  {
    id: "myelin",
    chapter: "Coordination & Control",
    difficulty: "Foundation",
    stem: "Myelin increases conduction speed mainly because action potentials are regenerated:",
    options: ["At every point on the membrane", "Only inside the cell body", "At nodes of Ranvier", "Inside synaptic vesicles"],
    answer: 2,
    explanation: "Myelin insulates internodes, so local current travels rapidly and action potentials are regenerated at exposed nodes of Ranvier.",
  },
  {
    id: "synaptic-calcium",
    chapter: "Coordination & Control",
    difficulty: "Challenge",
    stem: "Voltage-gated calcium channels in a presynaptic terminal are blocked. Which event is reduced first?",
    options: ["Neurotransmitter exocytosis", "Receptor synthesis in the nucleus", "Myelin formation", "Sodium pumping in every neuron"],
    answer: 0,
    explanation: "Calcium entry triggers synaptic vesicles to fuse with the presynaptic membrane and release neurotransmitter.",
  },
  {
    id: "refractory-period",
    chapter: "Coordination & Control",
    difficulty: "Standard",
    stem: "The refractory period helps an action potential move in one direction because the membrane immediately behind it:",
    options: ["Cannot be re-excited normally", "Has no ions", "Becomes permanently positive", "Loses its phospholipids"],
    answer: 0,
    explanation: "Recently activated sodium channels are inactivated, so the region just behind the impulse cannot immediately fire again.",
  },
  {
    id: "test-cross",
    chapter: "Inheritance",
    difficulty: "Standard",
    stem: "An organism showing a dominant phenotype is crossed with a homozygous recessive organism. The purpose is to determine the unknown organism's:",
    options: ["Age", "Genotype", "Chromosome number", "Mutation rate"],
    answer: 1,
    explanation: "A test cross reveals whether the dominant-looking parent is homozygous or heterozygous from the phenotypes of its offspring.",
  },
  {
    id: "independent-assortment",
    chapter: "Inheritance",
    difficulty: "Challenge",
    stem: "Independent assortment arises most directly from the random orientation of:",
    options: ["Homologous chromosome pairs at metaphase I", "Sister chromatids at prophase I", "Ribosomes during translation", "Genes during DNA replication"],
    answer: 0,
    explanation: "Each homologous pair aligns independently at metaphase I, producing different combinations of maternal and paternal chromosomes in gametes.",
  },
  {
    id: "incomplete-dominance",
    chapter: "Inheritance",
    difficulty: "Foundation",
    stem: "Red flowers crossed with white flowers produce pink heterozygotes. This pattern is:",
    options: ["Complete dominance", "Incomplete dominance", "Sex linkage", "Polyploidy"],
    answer: 1,
    explanation: "In incomplete dominance the heterozygote has an intermediate phenotype rather than matching either homozygote.",
  },
  {
    id: "x-linked",
    chapter: "Inheritance",
    difficulty: "Challenge",
    stem: "Why are X-linked recessive traits often expressed more frequently in males?",
    options: ["Males have two X chromosomes", "A male has only one allele for most X-linked genes", "The Y chromosome carries a dominant copy of every gene", "Male cells do not undergo mitosis"],
    answer: 1,
    explanation: "A male is hemizygous for most X-linked genes, so a recessive allele on his single X chromosome has no second allele to mask it.",
  },
  {
    id: "memory-cells",
    chapter: "Immunity",
    difficulty: "Foundation",
    stem: "A secondary immune response is faster mainly because the first exposure produced:",
    options: ["More skin", "Fewer antigen receptors", "Permanent fever", "Memory lymphocytes"],
    answer: 3,
    explanation: "Memory B and T cells persist after the primary response and expand rapidly when the same antigen returns.",
  },
  {
    id: "antigen-presentation",
    chapter: "Immunity",
    difficulty: "Challenge",
    stem: "A dendritic cell displays an extracellular pathogen-derived peptide on MHC class II. Which cell is activated most directly?",
    options: ["Helper T cell", "Red blood cell", "Platelet", "Skeletal muscle cell"],
    answer: 0,
    explanation: "CD4 helper T cells recognize antigen presented on MHC class II and coordinate adaptive immune responses.",
  },
  {
    id: "vaccine-response",
    chapter: "Immunity",
    difficulty: "Standard",
    stem: "A vaccine protects without causing the full disease primarily by:",
    options: ["Eliminating all white blood cells", "Generating antigen-specific memory", "Preventing every mutation", "Replacing innate immunity"],
    answer: 1,
    explanation: "Vaccination exposes the immune system to safe antigenic material, producing memory cells that support a stronger later response.",
  },
  {
    id: "innate-immunity",
    chapter: "Immunity",
    difficulty: "Standard",
    stem: "Which feature best distinguishes innate immunity from adaptive immunity?",
    options: ["It always improves after each exposure", "It responds rapidly through broadly recognizing mechanisms", "It depends only on antibodies", "It is absent at birth"],
    answer: 1,
    explanation: "Innate defences act rapidly and recognize broad danger patterns. Adaptive responses are antigen-specific and generate stronger memory.",
  },
  {
    id: "water-solvent",
    chapter: "Biological Molecules",
    difficulty: "Foundation",
    stem: "Why can water transport many ions and polar molecules through blood plasma and cytoplasm?",
    options: ["Its molecules are non-polar", "Its polarity surrounds and separates charged particles", "It has no intermolecular attractions", "It converts every solute into a lipid"],
    answer: 1,
    explanation: "Water is polar. Its partially charged regions form hydration shells around ions and interact with other polar substances, allowing them to remain dispersed in solution.",
  },
  {
    id: "polysaccharide-hydrolysis",
    chapter: "Biological Molecules",
    difficulty: "Standard",
    stem: "A storage polysaccharide is completely hydrolysed. Which change is expected in the reaction mixture?",
    options: ["Fewer reducing-sugar molecules", "More peptide bonds", "More monosaccharide molecules", "Formation of phospholipid bilayers"],
    answer: 2,
    explanation: "Hydrolysis uses water to break glycosidic bonds, releasing the monosaccharide units from which the polysaccharide was built.",
  },
  {
    id: "phospholipid-bilayer",
    chapter: "Biological Molecules",
    difficulty: "Standard",
    stem: "Phospholipids spontaneously form bilayers in water mainly because each molecule:",
    options: ["Has a hydrophilic head and hydrophobic tails", "Contains two hydrophilic tails", "Is made entirely of amino acids", "Forms covalent bonds with every neighbouring molecule"],
    answer: 0,
    explanation: "The polar heads interact with water while the non-polar fatty-acid tails avoid it. This amphipathic character drives bilayer formation.",
  },
  {
    id: "protein-denaturation-level",
    chapter: "Biological Molecules",
    difficulty: "Challenge",
    stem: "A globular protein is heat-denatured without hydrolysis. Which feature is most likely to remain intact?",
    options: ["Its precise active-site shape", "All hydrogen bonds", "Its normal tertiary structure", "The amino-acid sequence of each polypeptide"],
    answer: 3,
    explanation: "Denaturation disrupts interactions that maintain secondary and tertiary structure, but it does not normally break the peptide bonds of the primary amino-acid sequence.",
  },
  {
    id: "bile-duct-blockage",
    chapter: "Digestion",
    difficulty: "Standard",
    stem: "A bile duct is completely blocked while pancreatic secretion remains normal. Absorption of which nutrient class should decline most sharply?",
    options: ["Monosaccharides", "Amino acids", "Lipids", "Mineral ions"],
    answer: 2,
    explanation: "Bile salts emulsify fats and help form micelles, increasing access for lipase and carrying lipid digestion products to the intestinal surface.",
  },
  {
    id: "pepsin-small-intestine",
    chapter: "Digestion",
    difficulty: "Foundation",
    stem: "Why does pepsin lose most of its activity after acidic chyme enters the small intestine?",
    options: ["Bicarbonate raises the pH away from pepsin's optimum", "Pepsin is converted into bile", "All proteins have already been absorbed in the stomach", "The small intestine contains no water"],
    answer: 0,
    explanation: "Pancreatic bicarbonate neutralizes gastric acid. Pepsin is adapted to strongly acidic conditions, so the higher intestinal pH reduces its activity.",
  },
  {
    id: "villus-lacteal",
    chapter: "Digestion",
    difficulty: "Standard",
    stem: "Damage limited to the lacteals inside intestinal villi would most directly reduce the transport of:",
    options: ["Glucose into blood capillaries", "Amino acids into the hepatic portal vein", "Water by osmosis", "Chylomicrons into the lymphatic system"],
    answer: 3,
    explanation: "Absorbed long-chain lipids are repackaged as chylomicrons and enter lacteals, whereas most sugars and amino acids enter blood capillaries.",
  },
  {
    id: "sodium-glucose-cotransport",
    chapter: "Digestion",
    difficulty: "Challenge",
    stem: "The sodium–potassium pumps of intestinal epithelial cells stop. Which absorptive process should weaken as the sodium gradient collapses?",
    options: ["Simple diffusion of lipid-soluble molecules", "Sodium–glucose co-transport from the lumen", "Hydrolysis of proteins in the stomach", "Emulsification by bile salts"],
    answer: 1,
    explanation: "The basolateral sodium–potassium pump maintains the sodium gradient that powers secondary active co-transport of sodium and glucose across the apical membrane.",
  },
  {
    id: "emphysema-surface-area",
    chapter: "Respiration",
    difficulty: "Foundation",
    stem: "Destruction of alveolar walls in emphysema lowers gas-exchange efficiency mainly by reducing:",
    options: ["The surface area available for diffusion", "The concentration of nitrogen in air", "The number of ribs", "The solubility of glucose"],
    answer: 0,
    explanation: "Alveolar walls create a very large exchange surface. Their destruction produces larger air spaces with less total surface area for diffusion.",
  },
  {
    id: "carbon-monoxide-haemoglobin",
    chapter: "Respiration",
    difficulty: "Standard",
    stem: "A person inhales carbon monoxide. Tissue oxygen delivery falls first because carbon monoxide:",
    options: ["Thickens the pleural membranes", "Stops all movement of the diaphragm", "Competes strongly for haemoglobin binding sites", "Changes oxygen into carbon dioxide"],
    answer: 2,
    explanation: "Carbon monoxide binds haemoglobin with very high affinity, reducing both oxygen-carrying capacity and the release of remaining bound oxygen.",
  },
  {
    id: "exercise-diffusion-gradient",
    chapter: "Respiration",
    difficulty: "Challenge",
    stem: "During exercise, which change helps maintain a steep oxygen diffusion gradient from alveoli into blood?",
    options: ["Slower pulmonary blood flow", "Faster removal of oxygenated blood from alveolar capillaries", "Complete closure of bronchioles", "Accumulation of oxygen inside red cells"],
    answer: 1,
    explanation: "Increased pulmonary blood flow carries oxygenated blood away and brings more deoxygenated blood to the alveoli, helping preserve the partial-pressure gradient.",
  },
  {
    id: "thickened-alveolar-membrane",
    chapter: "Respiration",
    difficulty: "Standard",
    stem: "Fluid accumulation thickens the alveolar–capillary barrier. According to diffusion principles, oxygen transfer should fall because:",
    options: ["Surface area necessarily becomes infinite", "Oxygen molecules stop moving randomly", "Blood becomes a solid", "The diffusion distance increases"],
    answer: 3,
    explanation: "Diffusion rate decreases as diffusion distance increases. A thicker barrier therefore slows oxygen movement even if the pressure gradient remains present.",
  },
  {
    id: "adh-collecting-duct",
    chapter: "Homeostasis",
    difficulty: "Foundation",
    stem: "After heavy sweating, increased ADH most directly causes the collecting ducts to:",
    options: ["Become more permeable to water", "Stop receiving filtrate", "Secrete glucose into urine", "Destroy the medullary gradient"],
    answer: 0,
    explanation: "ADH promotes insertion of aquaporins, increasing water reabsorption from the collecting ducts and producing a smaller volume of concentrated urine.",
  },
  {
    id: "loop-henle-gradient",
    chapter: "Homeostasis",
    difficulty: "Challenge",
    stem: "The countercurrent arrangement of the loop of Henle is most important for establishing:",
    options: ["A high glucose concentration in urine", "An osmotic gradient in the renal medulla", "A pressure gradient in the aorta", "An acidic environment in the stomach"],
    answer: 1,
    explanation: "Opposing flow and different permeabilities in the loop multiply a medullary osmotic gradient, which later allows water reabsorption from collecting ducts.",
  },
  {
    id: "negative-feedback-fever",
    chapter: "Homeostasis",
    difficulty: "Standard",
    stem: "In a negative-feedback pathway, an effective response must ultimately:",
    options: ["Amplify the original deviation", "Operate without a receptor", "Move the regulated variable back toward its set range", "Continue unchanged after balance returns"],
    answer: 2,
    explanation: "Negative feedback opposes the initial change. The response diminishes as the regulated condition returns toward its normal range.",
  },
  {
    id: "beta-cell-damage",
    chapter: "Homeostasis",
    difficulty: "Standard",
    stem: "Selective destruction of pancreatic beta cells most directly impairs the response to:",
    options: ["Falling blood glucose through glucagon", "Rising body temperature through sweating", "Falling water potential through ADH", "Rising blood glucose through insulin"],
    answer: 3,
    explanation: "Beta cells secrete insulin when blood glucose rises. Loss of these cells weakens glucose uptake and storage, allowing hyperglycaemia.",
  },
  {
    id: "sarcomere-bands",
    chapter: "Support & Movement",
    difficulty: "Challenge",
    stem: "During sarcomere shortening, which pattern is expected?",
    options: ["A band shortens while I band is constant", "I band and H zone narrow while A band remains constant", "Actin filaments become shorter", "Myosin filaments disappear"],
    answer: 1,
    explanation: "Thin filaments slide farther over thick filaments. Their lengths do not change, so the A band stays constant while the I band and H zone narrow.",
  },
  {
    id: "atp-crossbridge-release",
    chapter: "Support & Movement",
    difficulty: "Standard",
    stem: "Which step of the cross-bridge cycle requires a fresh ATP molecule to bind directly to myosin?",
    options: ["Exposure of actin sites by calcium", "Release of acetylcholine", "Detachment of myosin from actin", "Diffusion of calcium from blood"],
    answer: 2,
    explanation: "ATP binding lowers myosin's affinity for actin and causes cross-bridge detachment. ATP hydrolysis then re-cocks the myosin head.",
  },
  {
    id: "calcium-troponin",
    chapter: "Support & Movement",
    difficulty: "Foundation",
    stem: "Calcium initiates skeletal-muscle contraction by binding to:",
    options: ["Troponin, shifting tropomyosin from actin sites", "Myosin, dissolving the thick filament", "Collagen, shortening tendons", "ATP synthase, pumping sodium"],
    answer: 0,
    explanation: "Calcium binds troponin, altering the troponin–tropomyosin complex and exposing myosin-binding sites on actin.",
  },
  {
    id: "osteoporosis-bone-density",
    chapter: "Support & Movement",
    difficulty: "Standard",
    stem: "Which change best explains the increased fracture risk in osteoporosis?",
    options: ["Excess synovial fluid in every joint", "Complete conversion of bone into cartilage", "Permanent contraction of all skeletal muscles", "Loss of bone mass and deterioration of bone microstructure"],
    answer: 3,
    explanation: "Osteoporosis weakens bone through reduced mass and disrupted internal architecture, so ordinary loads are more likely to cause fractures.",
  },
  {
    id: "lh-surge-ovulation",
    chapter: "Reproduction",
    difficulty: "Foundation",
    stem: "Which hormonal event most directly triggers ovulation in a typical menstrual cycle?",
    options: ["A surge in luteinising hormone", "A permanent fall in FSH from birth", "A sudden rise in ADH", "Release of thyroxine from the ovary"],
    answer: 0,
    explanation: "High oestrogen from the mature follicle produces positive feedback that generates an LH surge, triggering ovulation.",
  },
  {
    id: "progesterone-withdrawal",
    chapter: "Reproduction",
    difficulty: "Standard",
    stem: "If fertilisation does not occur, degeneration of the corpus luteum promotes menstruation mainly through a fall in:",
    options: ["Testosterone only", "Progesterone and oestrogen", "ADH and aldosterone", "Insulin and glucagon"],
    answer: 1,
    explanation: "The corpus luteum supports the endometrium by secreting progesterone and oestrogen. Their decline causes the uterine lining to break down.",
  },
  {
    id: "acrosome-reaction",
    chapter: "Reproduction",
    difficulty: "Challenge",
    stem: "Failure of the acrosome reaction would most directly prevent a sperm from:",
    options: ["Producing ATP in mitochondria", "Completing meiosis in the testes", "Penetrating the egg's surrounding layers", "Carrying a haploid nucleus"],
    answer: 2,
    explanation: "The acrosome releases enzymes that help the sperm pass through the egg's protective extracellular layers before membrane fusion.",
  },
  {
    id: "placental-barrier",
    chapter: "Reproduction",
    difficulty: "Standard",
    stem: "Maternal and fetal blood normally remain in separate circulations at the placenta. Exchange is still efficient because:",
    options: ["Every fetal capillary opens into a maternal artery", "Only hormones cross the placenta", "Fetal blood contains no plasma", "The exchange barrier is thin and richly supplied with vessels"],
    answer: 3,
    explanation: "A thin placental barrier and extensive blood supply maintain short diffusion distances and concentration gradients without direct mixing of the two bloodstreams.",
  },
  {
    id: "antibiotic-selection",
    chapter: "Evolution",
    difficulty: "Foundation",
    stem: "After antibiotic treatment, resistant bacteria become common. The most accurate explanation is that the antibiotic:",
    options: ["Selected resistant variants already present in the population", "Taught every bacterium how to resist", "Prevented all bacterial reproduction", "Converted viruses into bacteria"],
    answer: 0,
    explanation: "Resistance variants arise before exposure through mutation or gene transfer. Antibiotic treatment removes susceptible competitors and increases the relative success of resistant cells.",
  },
  {
    id: "homologous-structures",
    chapter: "Evolution",
    difficulty: "Standard",
    stem: "The same underlying forelimb bone pattern in whales, bats and humans is strongest evidence for:",
    options: ["Identical present-day functions", "Common ancestry followed by divergent evolution", "Inheritance of acquired characters", "Absence of natural selection"],
    answer: 1,
    explanation: "Homologous structures share an underlying developmental origin despite different functions, supporting descent from a common ancestor and later divergence.",
  },
  {
    id: "hardy-weinberg-change",
    chapter: "Evolution",
    difficulty: "Challenge",
    stem: "A large randomly mating population has no mutation, migration or selection. Which outcome is expected across generations?",
    options: ["Every recessive allele disappears", "All individuals become heterozygous", "Allele frequencies remain approximately constant", "Natural selection becomes stronger each generation"],
    answer: 2,
    explanation: "These conditions approximate Hardy–Weinberg equilibrium, under which allele and genotype frequencies remain stable apart from sampling error.",
  },
  {
    id: "founder-effect",
    chapter: "Evolution",
    difficulty: "Standard",
    stem: "A few individuals colonise an isolated island and carry allele frequencies unlike the source population. This is an example of:",
    options: ["Artificial selection", "Convergent evolution", "Gene flow into a large population", "The founder effect"],
    answer: 3,
    explanation: "A new population founded by a small sample may begin with unrepresentative allele frequencies, a form of genetic drift called the founder effect.",
  },
  {
    id: "sticky-ends",
    chapter: "Biotechnology",
    difficulty: "Foundation",
    stem: "Why are complementary sticky ends useful when constructing recombinant DNA?",
    options: ["They base-pair and align DNA fragments for ligase", "They translate DNA without ribosomes", "They destroy every plasmid marker", "They prevent all mutation"],
    answer: 0,
    explanation: "Complementary single-stranded overhangs hydrogen-bond, holding the fragments in the correct alignment so DNA ligase can seal the sugar–phosphate backbone.",
  },
  {
    id: "plasmid-selection-marker",
    chapter: "Biotechnology",
    difficulty: "Standard",
    stem: "After bacterial transformation, an antibiotic-resistance gene on the plasmid is used mainly to:",
    options: ["Force the insert to replicate outside cells", "Identify cells that received the plasmid", "Convert the plasmid into a chromosome", "Measure the protein's tertiary structure"],
    answer: 1,
    explanation: "Growth on the matching antibiotic selects transformed cells carrying the plasmid. Additional screening may still be needed to confirm that the desired insert is present.",
  },
  {
    id: "pcr-cycle-order",
    chapter: "Biotechnology",
    difficulty: "Standard",
    stem: "Which sequence correctly orders one PCR cycle?",
    options: ["Extension → denaturation → translation", "Ligation → transcription → annealing", "Denaturation → primer annealing → extension", "Annealing → meiosis → replication"],
    answer: 2,
    explanation: "Heat separates the DNA strands, cooling allows primers to anneal, and a thermostable polymerase extends from those primers.",
  },
  {
    id: "hybridoma-monoclonal",
    chapter: "Biotechnology",
    difficulty: "Challenge",
    stem: "Why is an antibody-producing B lymphocyte fused with a myeloma cell during hybridoma production?",
    options: ["To remove antibody specificity", "To create a bacteriophage", "To stop every cell division", "To combine specific antibody production with prolonged cell division"],
    answer: 3,
    explanation: "The B cell provides the desired antibody specificity, while the myeloma partner contributes the ability to divide repeatedly in culture.",
  },
];

export const quizChapters = Array.from(new Set(quizQuestions.map((question) => question.chapter)));
