'use client';
import {useState} from 'react';
import type {QuizQuestion} from './questions';
export function QuestionVisual({question}:{question:QuizQuestion}){const v=question.visual;if(!v)return null;return <figure className="question-visual"><figcaption>{v.caption}</figcaption>{v.kind==='table'?<div className="question-table-scroll"><table><thead><tr>{v.headers.map(h=><th scope="col" key={h}>{h}</th>)}</tr></thead><tbody>{v.rows.map((row,i)=><tr key={i}>{row.map((cell,j)=><td key={j}>{cell}</td>)}</tr>)}</tbody></table></div>:<ol className="question-flow">{v.nodes.map((n,i)=><li key={i}>{n}{i<v.nodes.length-1&&<span aria-hidden="true"> → </span>}</li>)}</ol>}</figure>;}
export function QuestionReport({question}:{question:QuizQuestion}){
 const[reason,R]=useState('Possible incorrect answer'),[note,N]=useState(''),[status,S]=useState('');
 const report=()=>`Biology with Hamza — question report\nQuestion ID: ${question.id}\nChapter: ${question.chapter}\nIssue: ${reason}\nQuestion: ${question.stem}\n${question.options.map((o,i)=>`${String.fromCharCode(65+i)}. ${o}`).join('\n')}${question.visual?"\nFigure data: "+JSON.stringify(question.visual):""}\nMarked answer: ${question.options[question.answer]}\nNotes: ${note.trim()}\nPage: https://hamzaramzan.online/practice/\n`;
 return <details className="question-report"><summary>Report a question · {question.id}</summary><p>Prepare a report to share with your teacher through your usual contact channel. Nothing is sent automatically.</p><label>Issue<select value={reason} onChange={e=>R(e.target.value)}>{['Possible incorrect answer','Ambiguous wording','Diagram or table issue','Typo','Other feedback'].map(r=><option key={r}>{r}</option>)}</select></label><label>What should we check?<textarea value={note} maxLength={1000} onChange={e=>N(e.target.value)} rows={3}/></label><div><button type="button" onClick={async()=>{try{await navigator.clipboard.writeText(report());S('Report copied. Paste it into your message to the teacher.');}catch{S('Copy is unavailable. Use Download report instead.');}}}>Copy report</button><button type="button" onClick={()=>{const u=URL.createObjectURL(new Blob([report()],{type:'text/plain'})),a=document.createElement('a');a.href=u;a.download=`question-report-${question.id}.txt`;a.click();URL.revokeObjectURL(u);S('Report downloaded. It has not been sent.');}}>Download report</button></div><p role="status">{status}</p></details>;
}
