'use client';
import Link from 'next/link';
import {useEffect,useState} from 'react';
import {quizQuestions,quizChapters} from '../practice/questions';
import {QuestionReport,QuestionVisual} from '../practice/question-tools';
import {learningChapters} from '../learn/catalogue';
import {chapterStats,questionVersion,reviewPool,type Attempt} from './model';
import {useProfile,useRevision,revisionBackup,parseBackup,restoreBackup,clearRevision} from './store';
const bank=new Map(quizQuestions.map(q=>[q.id,q]));
const when=(time:number)=>new Intl.DateTimeFormat('en-PK',{day:'numeric',month:'short',hour:'numeric',minute:'2-digit'}).format(time);
const modeName={fresh:'Fresh practice',mistakes:'Mistake practice',due:'Scheduled review',retry:'Immediate retry'};
function AttemptDetails({attempt}:{attempt:Attempt}){return <details className="revision-attempt"><summary><span>{when(attempt.at)}<small>{modeName[attempt.mode]} · {attempt.results.length} questions</small></span><strong>{attempt.results.filter(r=>r.correct).length}/{attempt.results.length}</strong></summary><div>{attempt.results.map((r,i)=>{const current=bank.get(r.id),same=current&&questionVersion(current)===r.version;return <details className="revision-result" key={r.id}><summary>{i+1}. {r.correct?'✓':'↺'} {r.stem}</summary>{same&&<QuestionVisual question={current}/>}<p>Your answer: <strong>{r.selected??'Unanswered'}</strong></p><p>Correct answer at the time: <strong>{r.answer}</strong></p>{same?<><p>{current.explanation}</p><QuestionReport question={current}/></>:<p>This question has been revised or retired. The answer snapshot is preserved, but it will not be included in review tests.</p>}</details>;})}</div></details>;}
export function RevisionDashboard(){
 const profile=useProfile(),data=useRevision(profile?.id??null);
 const[tab,T]=useState('Overview'),[chapter,C]=useState('All chapters'),[query,Q]=useState(''),[status,F]=useState('Needs practice'),[page,P]=useState(1),[message,M]=useState(''),[pending,I]=useState<ReturnType<typeof parseBackup>|null>(null),[confirmClear,K]=useState(false),[now,N]=useState(0);
 useEffect(()=>{const update=()=>N(Date.now());const initial=setTimeout(update,0),timer=setInterval(update,60000);return()=>{clearTimeout(initial);clearInterval(timer);};},[]);
 const due=reviewPool(data,quizQuestions,'due',now),needs=reviewPool(data,quizQuestions,'mistakes',now);
 const currentReviews=Object.values(data.review).filter(r=>{const q=bank.get(r.id);return q&&questionVersion(q)===r.version;});
 const stats=chapterStats(data,quizChapters),attempted=stats.filter(s=>s.seen),weak=[...attempted].filter(s=>s.seen>=5).sort((a,b)=>(a.accuracy??100)-(b.accuracy??100)).filter(s=>(s.accuracy??100)<80).slice(0,3);
 const nextDue=currentReviews.filter(r=>r.nextDue>now).sort((a,b)=>a.nextDue-b.nextDue)[0];
 const notebook=currentReviews.filter(r=>{const q=bank.get(r.id)!;return (chapter==='All chapters'||q.chapter===chapter)&&`${q.stem} ${q.chapter} ${q.id}`.toLowerCase().includes(query.toLowerCase().trim())&&(status==='All saved mistakes'||status==='Due now'&&r.nextDue<=now||status==='Needs practice'&&r.streak<2);}).sort((a,b)=>a.nextDue-b.nextDue);
 const pages=Math.max(1,Math.ceil(notebook.length/8)),currentPage=Math.min(page,pages);
 function exportBackup(){if(!profile)return;const u=URL.createObjectURL(new Blob([revisionBackup(profile,data)],{type:'application/json'})),a=document.createElement('a');a.href=u;a.download='biology-revision-backup.json';a.click();URL.revokeObjectURL(u);M('Revision backup downloaded. It includes your name, local ID and practice records.');}
 return <><header className="learning-heading"><p className="eyebrow">TURN MISTAKES INTO PROGRESS</p><h1>Your next step, made clear.</h1><p>Learn from each attempt. Revisit the difficult ideas after a little time.</p></header>
 {!profile?<section className="revision-empty"><h2>Start with your practice ID.</h2><p>Create a local profile in Practice, or restore an existing revision backup below. Your results will appear here after your next completed attempt.</p><Link className="button button-dark" href="/practice">Create a practice ID ↗</Link></section>:<>
 <div className="revision-profile"><span><strong>{profile.name}</strong> · {profile.id}</span><Link href="/practice">Open practice ↗</Link></div>
 <div className="revision-summary"><div><strong>{data.attempts.length}</strong><span>saved attempts</span></div><div><strong>{needs.length}</strong><span>mistakes to revisit</span></div><div><strong>{due.length}</strong><span>reviews due now</span></div><div><strong>{attempted.length}/16</strong><span>chapters practised fresh</span></div></div>
 <div className="revision-tabs" role="group" aria-label="Revision views">{['Overview','Mistake notebook','Attempt history'].map(t=><button type="button" key={t} aria-pressed={tab===t} onClick={()=>T(t)}>{t}</button>)}</div>
 {tab==='Overview'&&<><section className="revision-next"><div><p className="eyebrow">YOUR NEXT SESSION</p><h2>{due.length?'Time to retrieve what you learned.':needs.length?'Repair the idea, then revisit it.':'Begin with a fresh chapter test.'}</h2><p>{due.length?`${due.length} saved questions are due. Try recalling the answers before opening the explanations.`:nextDue?`Your next scheduled review is ${when(nextDue.nextDue)}. You can practise now; early retries do not advance the interval.`:'Your completed attempts will build a useful revision map. Scores here describe this practice bank, not a predicted exam result.'}</p></div><div className="revision-next-actions"><Link className="button button-dark" href={due.length?'/practice?mode=due':'/practice'}>{due.length?'Start due review':'Start fresh practice'} ↗</Link>{needs.length>0&&<Link className="button button-outline" href="/practice?mode=mistakes">Practise mistakes ↗</Link>}</div></section>
 {weak.length>0&&<section className="revision-recommendations"><h2>Give these chapters another look</h2><p>Suggested from chapters with at least five different questions in fresh attempts.</p><div>{weak.map(s=>{const route=learningChapters.find(c=>c.title===s.chapter);return <Link key={s.chapter} href={'/learn/'+route?.slug}><small>{s.correct}/{s.seen} different questions correct</small><h3>{s.chapter}</h3><span>Revisit the explanation and activities ↗</span></Link>;})}</div></section>}
 <section className="revision-chapters"><h2>Chapter feedback</h2><p>Latest fresh-attempt answer per question, from your last 50 saved attempts. Retries and scheduled reviews are excluded. Unanswered questions count as missed. Fewer than five different questions is a small sample.</p><div className="revision-chapter-grid">{stats.map(s=><article key={s.chapter}><h3>{s.chapter}</h3><div><strong>{s.accuracy===null?'—':s.accuracy+'%'}</strong><span>{s.correct}/{s.seen} different questions correct · {s.attempts} fresh attempts</span></div><div className="chapter-meter" aria-hidden="true"><span style={{width:(s.accuracy??0)+'%'}}/></div><p>{!s.seen?'No fresh attempts yet':s.seen<5?'Small sample — practise more before drawing conclusions':s.accuracy!<60?'Revisit the core explanation':s.accuracy!<80?'Practise the remaining gaps':'Strong on the questions attempted'}</p><Link href={'/practice?chapter='+encodeURIComponent(s.chapter)}>Practise chapter ↗</Link></article>)}</div></section></>}
 {tab==='Mistake notebook'&&<section><div className="revision-filters"><label>Chapter<select value={chapter} onChange={e=>{C(e.target.value);P(1);}}><option>All chapters</option>{quizChapters.map(c=><option key={c}>{c}</option>)}</select></label><label>Search questions<input type="search" value={query} onChange={e=>{Q(e.target.value);P(1);}} placeholder="Topic, wording or question ID"/></label><label>Show<select value={status} onChange={e=>{F(e.target.value);P(1);}}>{['Needs practice','Due now','All saved mistakes'].map(s=><option key={s}>{s}</option>)}</select></label></div><p role="status">{notebook.length} saved questions match.</p><p className="revision-note">After a miss, review is due in 1 day. Correct answers at or after the due time move the interval to 3, 7, 14, 30 and 60 days. Immediate retries leave the due date unchanged. Two successful spaced reviews move a question out of “Needs practice”; it remains scheduled for reinforcement.</p>
 {!notebook.length&&<div className="revision-empty"><h3>No questions in this view.</h3><p>Try another filter or complete a fresh practice attempt.</p><Link href="/practice">Go to practice ↗</Link></div>}
 <div className="mistake-list">{notebook.slice((currentPage-1)*8,currentPage*8).map(r=>{const q=bank.get(r.id)!;return <article key={q.id}><div className="mistake-meta"><span>{q.chapter} · {q.difficulty}</span><strong>{r.nextDue<=now?'Due now':`Next: ${when(r.nextDue)}`}</strong></div><h3>{q.stem}</h3><QuestionVisual question={q}/><p>{r.wrongCount} miss{r.wrongCount===1?'':'es'} · {r.streak} successful spaced reviews · {r.lastCorrect?'Last answer correct':'Last attempt missed or unanswered'}</p><details><summary>Reveal answer and explanation</summary><p><strong>{q.options[q.answer]}</strong></p><p>{q.explanation}</p>{r.selected&&<p>Last submitted answer: {r.selected}</p>}</details><QuestionReport question={q}/></article>;})}</div>
 {pages>1&&<div className="article-pagination"><button disabled={currentPage===1} onClick={()=>P(currentPage-1)}>Previous</button><span>{currentPage} / {pages}</span><button disabled={currentPage===pages} onClick={()=>P(currentPage+1)}>Next</button></div>}</section>}
 {tab==='Attempt history'&&<section className="revision-history"><h2>Every attempt has something to teach.</h2><p>Your latest 50 completed attempts are kept. Detailed answer records start with this update; earlier score summaries remain in Practice.</p>{data.attempts.length?data.attempts.map(a=><AttemptDetails key={a.id} attempt={a}/>):<div className="revision-empty"><p>No completed attempts saved yet.</p><Link href="/practice">Start your first attempt ↗</Link></div>}</section>}
 </>}
 <div className="connected-entry"><h2>Take progress to another device.</h2><p>Use a complete-learning backup or an optional online account.</p><Link href="/account">Open account and backup tools ↗</Link></div><section className="revision-backup"><div><h2>Keep a copy of your progress.</h2><p>Records stay in this browser and belong to this local ID. Export a revision backup before changing devices or clearing browser data. Bookmarks and study notes use their separate backup in the learning workspace.</p>{profile&&<button onClick={exportBackup}>Export revision backup</button>}</div><div><label>Restore a revision backup<input type="file" accept=".json,application/json" onChange={async e=>{const f=e.target.files?.[0];if(!f)return;try{if(f.size>4_000_000)throw Error('Use a file smaller than 4 MB.');I(parseBackup(await f.text()));M('Backup checked. Confirm below to restore it.');}catch(err){M(err instanceof Error?err.message:'Could not read backup.');I(null);}e.target.value='';}}/></label>{pending&&<div><p>Restore <strong>{pending.profile.name}</strong> ({pending.profile.id}) with {pending.data.attempts.length} attempts? This switches the active local ID and replaces its revision records. Other IDs and study notes are kept.</p><button onClick={()=>{try{restoreBackup(pending);I(null);M('Revision backup restored.');}catch{M('Could not restore. Browser storage may be unavailable or full.');}}}>Restore this backup</button><button onClick={()=>I(null)}>Cancel</button></div>}</div><p role="status">{message}</p>{profile&&<div className="revision-reset">{!confirmClear?<button onClick={()=>K(true)}>Reset this ID’s revision records…</button>:<><p>This removes the notebook and detailed attempt history for {profile.name} from this browser. Export first if you want to keep them.</p><button onClick={()=>{try{clearRevision(profile.id);K(false);M('Revision records reset. Your study notes and local ID are kept.');}catch{M('Could not reset browser storage.');}}}>Confirm reset</button><button onClick={()=>K(false)}>Cancel</button></>}</div>}</section></>;
}
