import type {Metadata} from "next";
import Link from "next/link";
import {notFound} from "next/navigation";
import {Header,Footer} from "../../components";
import {activities,chapters,syllabusUrl} from "../activity-data";
import {ActivityPlayer} from "../activity-player";
const guides=["o-level-diffusion-osmosis-active-transport","viruses-structure-classification-replication","cellular-respiration-atp-production","biological-molecules-structure-and-function","cell-organelles-and-membrane-transport","nerve-impulse-and-synapse","enzymes-activation-energy-and-inhibition","evolution-lamarck-darwin-natural-selection","human-reproduction-and-hormonal-control","sliding-filament-muscle-contraction","mendelian-inheritance-and-crosses","cardiac-cycle-and-circulation","innate-vs-adaptive-immunity","cellular-respiration-atp-production","digestion-and-absorption","negative-feedback-made-simple","biotechnology-vaccines-diagnosis-gene-therapy"];
export function generateStaticParams(){return activities.map(a=>({slug:a.slug}));}
export async function generateMetadata({params}:{params:Promise<{slug:string}>}):Promise<Metadata>{const{slug}=await params;const a=activities.find(a=>a.slug===slug);return a?{title:a.title+" · Biology Lab",description:a.summary,alternates:{canonical:"/lab/"+slug}}:{};}
export default async function ActivityPage({params}:{params:Promise<{slug:string}>}){const{slug}=await params;const a=activities.find(a=>a.slug===slug);if(!a)notFound();const related=activities.filter(b=>b.chapter===a.chapter&&b.slug!==slug).slice(0,3);
 return <><Header/><main id="main-content" className="activity-detail wrap"><nav className="activity-breadcrumb" aria-label="Breadcrumb"><Link href="/lab">← All activities</Link><span>{chapters[a.chapter]}</span></nav><header className="activity-detail-heading"><p className="eyebrow">{a.kind.toUpperCase()}</p><h1>{a.title}</h1><p>{a.summary}</p></header><ActivityPlayer activity={a}/><section className="activity-connections"><div><h2>Take the next step</h2><p>Connect this activity with your lesson notes and chapter practice.</p><Link href={"/articles/"+guides[a.chapter]}>Read a related learning guide →</Link><Link href={a.chapter?"/practice?chapter="+encodeURIComponent(chapters[a.chapter]):"/practice"}>Practise {a.chapter?chapters[a.chapter]:"Biology"} →</Link><a href="https://drive.google.com/drive/folders/1EAxaYkqS2Ud3uDQhsgF_9Cz-3koChQKg?usp=sharing" target="_blank" rel="noreferrer">Open the student notes folder ↗</a></div><div><h2>Concepts and sources</h2><p>{a.chapter?"Curriculum connections: "+a.objectives.join(", ")+". Selected concepts, simplified for this activity.":"Extension activity for deeper Biology understanding."}</p><a href={a.source} target="_blank" rel="noreferrer">Read the supporting source ↗</a>{a.chapter>0&&<a href={syllabusUrl} target="_blank" rel="noreferrer">PMDC curriculum ↗</a>}<p className="model-note">Questions and explanations are original teaching material; these are not official exam questions.</p></div></section>{related.length>0&&<section className="activity-related"><h2>Keep exploring {chapters[a.chapter]}</h2><div className="activity-grid">{related.map(b=><Link href={"/lab/"+b.slug} className="activity-card" key={b.slug}><span className="activity-kind">{b.kind}</span><h3>{b.title}</h3><p>{b.summary}</p></Link>)}</div></section>}</main><Footer/></>;
}
