import test from 'node:test';import assert from 'node:assert/strict';import {build} from 'esbuild';
const b=await build({stdin:{contents:'export * from "./app/account/snapshot";export * from "./app/cambridge-practice/questions";export * from "./app/cambridge-practice/store";export * from "./app/cambridge-o-level/topics";export * from "./app/learn/catalogue";',resolveDir:process.cwd()},bundle:true,platform:'node',format:'esm',write:false});
const m=await import('data:text/javascript;base64,'+Buffer.from(b.outputFiles[0].text).toString('base64'));
function storage(){const values=new Map();return{getItem:k=>values.get(k)??null,setItem:(k,v)=>values.set(k,v),removeItem:k=>values.delete(k),values};}
globalThis.window={dispatchEvent:()=>{}};globalThis.localStorage=storage();
test('every Cambridge topic has two original structured questions and coherent marks',()=>{assert.equal(m.writtenQuestions.length,38);assert.equal(new Set(m.writtenQuestions.map(q=>q.id)).size,38);for(const t of m.cambridgeTopics)assert.equal(m.writtenQuestions.filter(q=>q.topic===t.slug).length,2,t.slug);for(const q of m.writtenQuestions){assert(q.points.length>=2&&q.points.length<=4);assert(q.model.trim().length>0);assert(m.commandGuides.some(c=>c.word===q.command));}assert.equal(m.commandDrills.length,10);});
test('all sixteen packs have a lesson, diagram, activities and recall questions',()=>{for(const c of m.learningChapters){assert(c.article);assert(c.article.sections.some(s=>s.diagram),c.slug);assert(c.activities.length);assert(c.article.checks.length>=2);assert(c.article.recap.length>=3);}});
test('complete snapshots roundtrip written answers, notes and checklist state',()=>{const s=m.captureSnapshot();s.study.completed=['/packs/cells/0'];s.study.notes={'/learn/cells':'My own explanation'};s.writing.records['5090-cells-1']={answer:'600 times',revealed:true,checked:[0,1],updatedAt:100};m.applySnapshot(s);assert.deepEqual(m.captureSnapshot().study,s.study);assert.deepEqual(m.captureSnapshot().writing,s.writing);assert(m.validSnapshot(m.parseSnapshot(JSON.stringify(s))));});
test('malformed, oversized and unsafe-path backups are rejected',()=>{const s=m.captureSnapshot();s.study.saved=['javascript:alert(1)'];assert(!m.validSnapshot(s));assert.throws(()=>m.parseSnapshot('x'.repeat(3_000_001)));assert.throws(()=>m.parseSnapshot('{"version":1}'));assert(!m.validWritten({version:1,records:{'5090-cells-1':{answer:'x',revealed:true,checked:[-1],updatedAt:1}}}));});
test('failed restore rolls already changed storage back',()=>{const before=m.captureSnapshot(),after=structuredClone(before);after.study.notes={'/learn/cells':'Changed'};const normal=localStorage.setItem;let fail=true;localStorage.setItem=(k,v)=>{if(k===m.CAMBRIDGE_KEY&&fail){fail=false;throw Error('Quota');}normal(k,v);};assert.throws(()=>m.applySnapshot(after));localStorage.setItem=normal;assert.deepEqual(m.captureSnapshot().study,before.study);});
test('unreadable local progress is never silently uploaded as empty',()=>{localStorage.setItem('bwh-learning-v1','broken');assert.throws(()=>m.captureSnapshot());localStorage.removeItem('bwh-learning-v1');});
