import type {Article} from '../article-data';import type {QuizQuestion} from '../practice/questions';import {deepFeedback} from '../practice/deep-feedback';
const escape=(s:string)=>s.replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]!));
const json=(v:unknown)=>JSON.stringify(v).replace(/</g,'\\u003c').replace(/\u2028/g,'\\u2028').replace(/\u2029/g,'\\u2029');
export function offlineDocument(title:string,article:Article,questions:QuizQuestion[]){
 const e=escape,content=article.sections.map(s=>`<section><h2>${e(s.heading)}</h2>${s.paragraphs.map(p=>`<p>${e(p)}</p>`).join('')}${s.points?`<ul>${s.points.map(p=>`<li>${e(p)}</li>`).join('')}</ul>`:''}${s.callout?`<aside>${e(s.callout)}</aside>`:''}${s.diagram?`<figure><figcaption>${e(s.diagram.title)}</figcaption><ol class="flow">${s.diagram.items.map(i=>`<li><strong>${e(i.label)}</strong><p>${e(i.detail)}</p></li>`).join('')}</ol><p>${e(s.diagram.caption)}</p></figure>`:''}${s.table?`<div class="scroll"><table><caption>${e(s.table.caption)}</caption><thead><tr>${s.table.headers.map(h=>`<th>${e(h)}</th>`).join('')}</tr></thead><tbody>${s.table.rows.map(row=>`<tr>${row.map(c=>`<td>${e(c)}</td>`).join('')}</tr>`).join('')}</tbody></table></div>`:''}</section>`).join('');
 return `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${e(title)} — Biology with Hamza offline pack</title><style>
 :root{color-scheme:light dark;--bg:#f5f3ea;--ink:#152d29;--panel:white;--line:#c5d3c6;--accent:#256758}*{box-sizing:border-box}body{margin:0;background:var(--bg);color:var(--ink);font:17px/1.8 system-ui,sans-serif}main{max-width:900px;margin:auto;padding:30px 22px 70px}h1{font-size:clamp(34px,7vw,60px);line-height:1.1}h2{line-height:1.3;font-size:28px}h3{line-height:1.5}section,figure,aside{margin:25px 0;padding:25px;background:var(--panel);border:1px solid var(--line);border-radius:16px}figure{margin-inline:0}.eyebrow{font-size:12px;letter-spacing:.12em;font-weight:800}.note{font-size:14px}button,select{font:inherit;padding:12px;border:1px solid var(--line);border-radius:9px;background:var(--panel);color:var(--ink);margin:5px;min-height:44px}button{cursor:pointer}button:disabled{opacity:.45;cursor:not-allowed}button:focus-visible,a:focus-visible{outline:3px solid var(--accent);outline-offset:3px}fieldset{border:0;padding:0}fieldset label{display:flex;align-items:flex-start;gap:12px;padding:14px;border:1px solid var(--line);margin:10px 0;border-radius:9px}input{margin-top:8px;flex-shrink:0}a{color:var(--accent)}.flow{padding-left:25px}.flow li{margin:18px 0}table{border-collapse:collapse;width:100%}th,td{border:1px solid var(--line);padding:10px;text-align:left}.scroll{overflow:auto}details{margin:15px 0}summary{cursor:pointer;font-weight:700}.hidden{display:none}.feedback{border-left:4px solid var(--accent);padding-left:15px}.actions{display:flex;gap:10px;flex-wrap:wrap}@media(prefers-color-scheme:dark){:root{--bg:#11221f;--ink:#ecf4eb;--panel:#1c312b;--line:#526d5d;--accent:#9cddb5}}@media print{:root{--bg:white;--ink:black;--panel:white;--line:#aaa;--accent:black}body{font-size:11pt}.no-print,#quiz{display:none}main{max-width:none;padding:0}section,figure{break-inside:avoid;border:0;padding:0}h2{font-size:18pt}a{color:black}}
 </style></head><body><main><p class="eyebrow">BIOLOGY WITH HAMZA · OFFLINE CHAPTER PACK · V5 · 06 OCT 2026</p><h1>${e(title)}</h1><p>${e(article.description)}</p><p class="note">This file works without internet after download. It contains notes, concept flows, recall questions and ${questions.length} practice MCQs. Offline quiz results are temporary and do not sync to the website. Video lessons and the 3D Atlas are not included. Download a new pack from the website when content is updated.</p><div class="actions no-print"><button id="print">Print notes / save PDF</button><a href="#quiz">Jump to offline practice</a></div><section><h2>Learning targets</h2><ul>${article.objectives.map(o=>`<li>${e(o)}</li>`).join('')}</ul></section>${content}<section><h2>Key-point recap</h2><ul>${article.recap.map(o=>`<li>${e(o)}</li>`).join('')}</ul></section><section><h2>Recall without looking</h2>${article.checks.map(c=>`<h3>${e(c.question)}</h3><details><summary>Show teaching answer</summary><p>${e(c.answer)}</p></details>`).join('')}</section><section id="quiz"><h2>Offline practice</h2><p>Randomised questions and answer choices. Lock each answer to move forward. There is no timer in this offline practice mode. Refreshing this file resets the attempt.</p><div id="setup"><label>Questions <select id="count"><option>10</option><option>25</option><option>100</option></select></label><button id="start">Start practice</button></div><div id="play" class="hidden"><p id="progress"></p><h3 id="stem" tabindex="-1"></h3><div id="visual"></div><fieldset id="options"><legend>Choose one answer</legend></fieldset><button id="lock" disabled>Lock answer & continue</button><button id="skip">Skip unanswered</button></div><div id="results" class="hidden"></div></section><p class="note">Original teaching notes and practice. Not an official exam paper. Online source: hamzaramzan.online. Concept-flow diagrams simplify the mechanisms.</p></main><script>
 const bank=${json(questions)},extra=${json(deepFeedback)};
 const el=id=>document.getElementById(id),safe=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
 const shuffle=a=>{a=[...a];for(let i=a.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[a[i],a[j]]=[a[j],a[i]];}return a;};
 let attempt=[],answers=[],index=0,draft=null;
 function visual(q){if(!q.visual)return '';const v=q.visual;return v.kind==='table'?'<div class="scroll"><table><caption>'+safe(v.caption)+'</caption><thead><tr>'+v.headers.map(x=>'<th>'+safe(x)+'</th>').join('')+'</tr></thead><tbody>'+v.rows.map(r=>'<tr>'+r.map(c=>'<td>'+safe(c)+'</td>').join('')+'</tr>').join('')+'</tbody></table></div>':'<p>'+safe(v.caption)+'</p><ol>'+v.nodes.map(n=>'<li>'+safe(n)+'</li>').join('')+'</ol>';}
 function show(){const q=attempt[index];el('progress').textContent='Question '+(index+1)+' / '+attempt.length;el('stem').textContent=q.stem;el('stem').focus();el('visual').innerHTML=visual(q);el('options').innerHTML='<legend>Choose one answer</legend>'+q.options.map((o,i)=>'<label><input type="radio" name="option" value="'+i+'"><span>'+String.fromCharCode(65+i)+'. '+safe(o)+'</span></label>').join('');el('options').querySelectorAll('input').forEach(input=>input.onchange=()=>{draft=Number(input.value);el('lock').disabled=false;});draft=null;el('lock').disabled=true;}
 function finish(){el('play').classList.add('hidden');el('results').classList.remove('hidden');const score=attempt.filter((q,i)=>answers[i]===q.answer).length;el('results').innerHTML='<h2>Your result: '+score+' / '+attempt.length+'</h2><p>Unanswered: '+answers.filter(a=>a===null).length+'. Results are only for this session.</p><button id="again">Choose another practice set</button>'+attempt.map((q,i)=>{const d=extra[q.id];return '<article><h3>'+safe(q.stem)+'</h3>'+visual(q)+'<p>Your answer: '+safe(q.options[answers[i]]||'Unanswered')+'</p><p><strong>Correct: '+safe(q.options[q.answer])+'</strong></p><p>'+safe(q.explanation)+'</p>'+(d?'<details><summary>Why each option works or fails</summary><ul>'+q.options.map(o=>'<li><strong>'+safe(o)+'</strong>: '+safe(d.options[o])+'</li>').join('')+'</ul></details><details><summary>Roman Urdu explanation</summary><p lang="ur-Latn">'+safe(d.romanUrdu)+'</p></details>':'')+'</article>';}).join('');el('again').onclick=()=>{el('setup').classList.remove('hidden');el('results').classList.add('hidden');};}
 function next(value){answers.push(value);index++;if(index===attempt.length)finish();else show();}
 el('start').onclick=()=>{attempt=shuffle(bank).slice(0,Math.min(Number(el('count').value),bank.length)).map(q=>{const options=shuffle(q.options);return {...q,options,answer:options.indexOf(q.options[q.answer])};});answers=[];index=0;el('setup').classList.add('hidden');el('results').classList.add('hidden');el('play').classList.remove('hidden');show();};el('lock').onclick=()=>{if(draft!==null)next(draft);};el('skip').onclick=()=>next(null);el('print').onclick=()=>window.print();
 </script></body></html>`;
}
