'use client';
import Link from 'next/link';
import {useEffect,useState} from 'react';
import {cambridgeTopics} from '../cambridge-o-level/topics';
import {writtenQuestions,commandGuides,commandDrills,type WrittenQuestion} from './questions';
import {useWritten,saveWritten,type WrittenRecord} from './store';
const blank:WrittenRecord={answer:'',revealed:false,checked:[],updatedAt:0};
function WrittenCard({q}:{q:WrittenQuestion}){
 const data=useWritten(),saved=data.records[q.id]??blank;
 const[draft,D]=useState<string|null>(null),[message,M]=useState('');
 const answer=draft??saved.answer;
 function commit(revealed:boolean,checked=saved.checked){const ok=saveWritten(q.id,{answer,revealed,checked,updatedAt:Date.now()});M(ok?(revealed?'Answer saved. Compare your response with the teaching points.':'Draft saved on this browser.'):'Could not save. Copy your answer before leaving this page.');if(ok)D(null);}
 return <article className="written-card"><div className="written-meta"><span>{cambridgeTopics.find(t=>t.slug===q.topic)?.title}</span><strong>{q.command} · {q.points.length} marks</strong></div><h2>{q.stem}</h2>{q.table&&<div className="pack-table"><table><caption>Illustrative experimental data</caption><thead><tr>{q.table.headers.map(h=><th key={h} scope="col">{h}</th>)}</tr></thead><tbody>{q.table.rows.map((row,i)=><tr key={i}>{row.map((c,j)=><td key={j}>{c}</td>)}</tr>)}</tbody></table></div>}<p className="writing-hint">{commandGuides.find(c=>c.word===q.command)?.action}</p><label>Your answer<textarea value={answer} onChange={e=>D(e.target.value)} readOnly={saved.revealed} maxLength={4000} rows={5} placeholder="Write your answer before revealing the marking points."/></label><div className="writing-actions">{!saved.revealed?<><button onClick={()=>commit(false)} disabled={!answer.trim()}>Save draft</button><button className="solid-action" onClick={()=>commit(true,[])} disabled={!answer.trim()}>Finish answer & reveal</button></>:<button onClick={()=>{if(saveWritten(q.id,{...blank,updatedAt:Date.now()})){D('');M('New attempt started. Your previous answer for this question was cleared.');}else M('Storage unavailable.');}}>Start a new answer</button>}</div><p role="status">{message}</p>{saved.revealed&&<section className="written-feedback"><h3>Mark your answer</h3><p>Tick each point you clearly made. This is self-assessment, not automatic or official marking. Equivalent scientific wording can be valid.</p><ul>{q.points.map((point,i)=><li key={point}><label><input type="checkbox" checked={saved.checked.includes(i)} onChange={()=>commit(true,saved.checked.includes(i)?saved.checked.filter(n=>n!==i):[...saved.checked,i])}/><span>{point}</span></label></li>)}</ul><p><strong>{saved.checked.filter(n=>n<q.points.length).length}/{q.points.length} points self-checked</strong></p><h3>One model answer</h3><p>{q.model}</p><p className="writing-tip"><strong>Exam habit:</strong> {q.tip}</p><Link href={'/cambridge-o-level/'+q.topic}>Revisit this topic ↗</Link></section>}</article>;
}
function CommandPractice(){const[index,I]=useState(0),[choice,C]=useState('');const d=commandDrills[index];return <section className="command-practice"><div><p className="eyebrow">READ THE INSTRUCTION</p><h2>What is the question asking?</h2><p>Choose the command word that best matches the task.</p></div><div><p className="command-prompt">{d.prompt}</p><div className="command-options">{commandGuides.map(c=><button key={c.word} disabled={!!choice} aria-pressed={choice===c.word} onClick={()=>C(c.word)}>{c.word}</button>)}</div>{choice&&<div role="status"><p><strong>{choice===d.answer?'Correct.':`Best match: ${d.answer}.`}</strong> {d.why}</p><button onClick={()=>{I((index+1)%commandDrills.length);C('');}}>Next exercise →</button></div>}<small>{index+1} / {commandDrills.length} command-word exercises</small></div></section>;}
export function CambridgePractice(){const[topic,T]=useState('all'),[command,C]=useState('all'),[query,Q]=useState(''),[page,P]=useState(1);const data=useWritten();
 useEffect(()=>{const timer=setTimeout(()=>{const t=new URLSearchParams(location.search).get('topic');if(t&&cambridgeTopics.some(c=>c.slug===t))T(t);},0);return()=>clearTimeout(timer);},[]);
 const questions=writtenQuestions.filter(q=>(topic==='all'||q.topic===topic)&&(command==='all'||q.command===command)&&q.stem.toLowerCase().includes(query.toLowerCase().trim()));const pages=Math.max(1,Math.ceil(questions.length/4)),current=Math.min(page,pages),completed=writtenQuestions.filter(q=>data.records[q.id]?.revealed).length;
 return <><div className="writing-summary"><strong>38 original questions · 19 topics</strong><span>{completed}/38 attempted on this browser</span><Link href="/account">Back up or sync your answers ↗</Link></div><CommandPractice/><details className="command-guide"><summary>Open the command-word reference</summary><div>{commandGuides.map(c=><article key={c.word}><h3>{c.word}</h3><p>{c.action}</p><small>{c.trap}</small></article>)}</div><p>Independent teaching guidance. Check the <a href="https://www.cambridgeinternational.org/Images/697330-2026-2028-syllabus.pdf" target="_blank" rel="noreferrer">official 5090 syllabus</a> for the full command-word list.</p></details><section className="written-library" id="questions"><div className="writing-filters"><label>Topic<select value={topic} onChange={e=>{T(e.target.value);P(1);}}><option value="all">All topics</option>{cambridgeTopics.map(t=><option key={t.slug} value={t.slug}>{t.title}</option>)}</select></label><label>Command word<select value={command} onChange={e=>{C(e.target.value);P(1);}}><option value="all">All command words</option>{commandGuides.map(c=><option key={c.word}>{c.word}</option>)}</select></label><label>Search questions<input type="search" value={query} onChange={e=>{Q(e.target.value);P(1);}} placeholder="For example, glucose"/></label></div><p role="status">{questions.length} questions match. Your latest saved response to each question is kept.</p>{!questions.length&&<p className="feature-empty">No matches. Try another topic or command word.</p>}<div className="written-list">{questions.slice((current-1)*4,current*4).map(q=><WrittenCard q={q} key={q.id}/>)}</div>{pages>1&&<div className="writing-pagination"><button disabled={current===1} onClick={()=>P(current-1)}>Previous</button><span>Page {current} of {pages}</span><button disabled={current===pages} onClick={()=>P(current+1)}>Next</button></div>}</section></>;
}
