import Image from "next/image";
import Link from "next/link";
import { ArticleCard, Footer, Header } from "./components";
import { articles, links, videos } from "./content";
import { Icon } from "./ui-icons";
import { EnzymeTeaser, LearningRoutes } from "./home-interactions";

export default function HomePage() {
  const featuredArticles = [articles.find(a => a.category === "MDCAT")!, articles.find(a => a.category === "Cambridge O Level")!, articles.find(a => a.category === "Study Strategy")!];
  return <><Header/><main id="main-content" className="home-page">
    <section className="studio-hero wrap" aria-labelledby="hero-title">
      <div className="studio-hero-copy"><p className="eyebrow"><span className="status-dot"/>MDCAT + CAMBRIDGE O LEVEL</p><h1 id="hero-title">Biology, made<br />to make <span>sense.</span></h1><p className="hero-description">Less memorising. More understanding.<br />Let’s turn the science of life into the subject you look forward to.</p><div className="hero-actions"><Link href="/practice" className="button button-dark">Find your starting point <Icon name="arrow"/></Link><a href={links.youtube} className="button button-outline" target="_blank" rel="noreferrer"><Icon name="play"/>Watch on YouTube</a></div><div className="hero-note"><span className="hero-note-symbol"><Icon name="check"/></span><p>Clear explanations. Real practice.<br /><strong>With Hamza Ramzan, your Biology teacher.</strong></p></div></div>
      <div className="studio-hero-visual"><div className="portrait-topline"><span>BIOLOGY WITH HAMZA</span><Icon name="sun"/></div><p className="portrait-word" aria-hidden="true">Stay<br />curious.</p><Image className="hero-portrait" src="/hamza-ramzan.webp" alt="Hamza Ramzan, Biology lecturer" width={1136} height={1476} sizes="(max-width: 760px) 95vw, 45vw" priority/><div className="portrait-name"><span>YOUR TEACHER</span><strong>Hamza Ramzan</strong><p>Senior Biology Lecturer · Academic Lead</p></div><a className="portrait-lesson" href={videos[0].href} target="_blank" rel="noreferrer"><span className="round-play"><Icon name="play"/></span><span><small>START WITH A LESSON</small><strong>Acellular Life, explained.</strong></span><Icon name="arrow"/></a></div>
    </section>
    <section className="trust-strip wrap" aria-label="Teaching experience"><div><strong>9+</strong><span>years teaching Biology</span></div><div><strong>100K+</strong><span>students reached</span></div><div><strong>2</strong><span>focused learning tracks</span></div><div><strong>5×</strong><span>Best Speaker of Punjab</span></div></section>
    <LearningRoutes/>
    <section className="lab-feature wrap" aria-labelledby="lab-feature-title"><div className="lab-feature-copy"><span className="pill"><Icon name="lab"/> NEW · THE BIOLOGY LAB</span><h2 id="lab-feature-title">Don’t just read it.<br /><em>Try it.</em></h2><p>Change one thing. See what happens. Explore the relationships behind enzymes, osmosis and inheritance with interactive models.</p><Link href="/lab" className="button button-lime">Step into the lab <Icon name="arrow"/></Link><div className="lab-feature-topics"><span>01 Enzyme activity</span><span>02 Osmosis</span><span>03 Genetic crosses</span></div></div><EnzymeTeaser/></section>
    <section className="atlas-home-card wrap"><div><span className="pill"><Icon name="layers"/> NEW · HUMAN ATLAS</span><h2>A different way<br />to see yourself.</h2><p>Explore 2,234 anatomical structures in 3D. Rotate the body, reveal its systems and get a closer look at the organs that make it work.</p><Link href="/atlas" className="button button-dark">Explore the Human Atlas <Icon name="arrow"/></Link></div><div className="atlas-home-options"><Link href="/atlas"><span>01</span><div><h3>Choose a region</h3><p>From head and neck to hands and feet.</p></div><Icon name="arrow"/></Link><Link href="/atlas"><span>02</span><div><h3>Peel back a layer</h3><p>Skeleton, muscles, nerves and organ systems.</p></div><Icon name="arrow"/></Link><Link href="/atlas"><span>03</span><div><h3>Meet an organ</h3><p>Search, isolate and rotate your selection.</p></div><Icon name="arrow"/></Link><small>Adult male reference anatomy · BodyParts3D</small></div></section>
    <section className="home-guides wrap" aria-labelledby="guides-title"><div className="section-heading"><div><p className="eyebrow">THE LEARNING JOURNAL</p><h2 id="guides-title">Big ideas.<br />Clear explanations.</h2></div><Link className="text-link" href="/articles">Explore all {articles.length} guides <Icon name="arrow"/></Link></div><div className="home-article-grid">{featuredArticles.map(a => <ArticleCard key={a.slug} article={a}/>)}</div></section>
    <section className="home-lessons wrap" aria-labelledby="lessons-title"><div className="section-heading"><div><p className="eyebrow">PULL UP A CHAIR</p><h2 id="lessons-title">Your next “oh, I get it.”</h2></div><Link className="text-link" href="/videos">Browse the lesson library <Icon name="arrow"/></Link></div><div className="lesson-showcase"><a className="featured-lesson" href={videos[0].href} target="_blank" rel="noreferrer"><div className="featured-lesson-art"><Image src={videos[0].image} alt="Acellular Life, lecture 1 with Hamza Ramzan" width={1280} height={720} sizes="(max-width: 760px) 92vw, 60vw"/><span className="featured-play"><Icon name="play"/></span><span className="video-tag">WATCH THE LESSON</span></div><div className="featured-lesson-copy"><div><p>{videos[0].label}</p><h3>{videos[0].title}</h3></div><Icon name="arrow"/></div></a><div className="lesson-side"><p className="eyebrow">KEEP THE MOMENTUM</p><h3>A chapter makes more sense when you connect the dots.</h3><p>Watch a lesson. Read the explanation. Then see what you can answer on your own.</p><a className="button button-dark" href={links.playlist} target="_blank" rel="noreferrer">Open the MDCAT playlist <Icon name="arrow"/></a><Link className="text-link" href="/resources">Find the lecture notes <Icon name="download"/></Link></div></div></section>
    <section className="home-about wrap"><div className="home-about-heading"><p className="eyebrow">MEET HAMZA</p><h2>Good teaching starts<br />with a better question.</h2></div><div className="home-about-copy"><p>“Why?” is often where the best Biology lesson begins. My approach connects the mechanisms, the diagrams and the exam questions—so the facts have somewhere to belong.</p><p>With 9+ years in the classroom and hundreds of thousands of learners reached, I’m building a space that makes Biology clearer, one concept at a time.</p><Link className="text-link" href="/about">A little more about me <Icon name="arrow"/></Link></div></section>
    <section className="community-card wrap"><div><span className="eyebrow">KEEP YOUR CURIOSITY CLOSE</span><h2>See you in the<br />next lesson.</h2><p>New explanations, study resources and a little encouragement along the way.</p></div><div className="community-links"><a href={links.youtube} target="_blank" rel="noreferrer"><Icon name="play"/><span><small>LEARN SOMETHING NEW</small><strong>Watch on YouTube</strong></span><Icon name="arrow"/></a><a href={links.whatsapp} target="_blank" rel="noreferrer"><Icon name="book"/><span><small>STAY IN THE LOOP</small><strong>Join the WhatsApp channel</strong></span><Icon name="arrow"/></a><a href={links.instagram} target="_blank" rel="noreferrer"><Icon name="sun"/><span><small>BEYOND THE CLASSROOM</small><strong>Follow on Instagram</strong></span><Icon name="arrow"/></a></div></section>
  </main><Footer/></>;
}
