"use client";
import Link from "next/link";
import {useState} from "react";
import {activities,chapters} from "./activity-data";
export function ActivityLibrary(){
 const[q,Q]=useState(""),[chapter,C]=useState("all"),[kind,K]=useState("all"),[page,P]=useState(0);
 const found=activities.filter(a=>(chapter==="all"||a.chapter===+chapter)&&(kind==="all"||a.kind===kind)&&[a.title,a.summary,chapters[a.chapter]].join(" ").toLowerCase().includes(q.trim().toLowerCase()));
 function clear(){Q("");C("all");K("all");P(0);}
 return <section className="activity-library wrap" aria-label="Choose a biology activity"><div className="activity-filters"><label>Search activities<input type="search" value={q} placeholder="Try nerve, enzymes, inheritance…" onChange={e=>{Q(e.target.value);P(0);}}/></label><label>Chapter<select value={chapter} onChange={e=>{C(e.target.value);P(0);}}><option value="all">All chapters</option>{chapters.map((c,i)=><option key={c} value={i}>{c}</option>)}</select></label><label>Activity type<select value={kind} onChange={e=>{K(e.target.value);P(0);}}><option value="all">All activity types</option>{["Model","Build a process","Sort & explain"].map(k=><option key={k}>{k}</option>)}</select></label></div><div className="activity-count"><p role="status">{found.length} activities · {found.length?("showing "+(page*12+1)+"–"+Math.min((page+1)*12,found.length)):"try another search"}</p><button className="text-button" onClick={clear}>Clear filters</button></div><div className="activity-grid">{found.slice(page*12,page*12+12).map(a=><Link className="activity-card" href={"/lab/"+a.slug} key={a.slug}><span className="activity-kind">{a.kind}</span><h2>{a.title}</h2><p>{a.summary}</p><footer><span>{chapters[a.chapter]}</span><strong aria-hidden="true">↗</strong></footer></Link>)}</div>{!found.length&&<div className="activity-empty"><h2>No matching activities</h2><p>Try a broader topic or clear your filters.</p></div>}{found.length>12&&<nav className="activity-pagination" aria-label="Activity pages"><button disabled={page===0} onClick={()=>P(p=>p-1)}>← Previous</button><span>Page {page+1} of {Math.ceil(found.length/12)}</span><button disabled={(page+1)*12>=found.length} onClick={()=>P(p=>p+1)}>Next →</button></nav>}</section>;
}
