"use client";
import {useState} from 'react';
type Param={label:string;min:number;max:number;step:number;start:number};
type Model={params:Param[];output:(v:number[])=>[string,number][];explanation:string;challenge:string;note:string};
const p=(label:string,min:number,max:number,start:number,step=1)=>({label,min,max,start,step});
const models:Record<string,Model>={
ventilation:{params:[p('Tidal volume (mL)',200,1000,500,25),p('Breaths per minute',6,40,12),p('Dead space (mL)',100,200,150,10)],output:([v,r,d])=>[['Minute ventilation (L/min)',v*r/1000],['Alveolar ventilation (L/min)',(v-d)*r/1000]],explanation:'Minute ventilation = tidal volume × frequency. Alveolar ventilation = (tidal volume − dead space) × frequency. Conducting passages contain air that does not exchange gases with blood there.',challenge:'Compare 500 mL × 12 breaths with 250 mL × 24 breaths at 150 mL dead space. Total ventilation is identical. Is alveolar ventilation?',note:'Illustrative adult values; fixed dead space. This does not calculate oxygen uptake, perfusion or disease.'},
'gas-exchange-surface':{params:[p('Available area (%)',10,100,100),p('Thickness (× baseline)',1,5,1,.25),p('Partial-pressure gradient (relative units)',0,80,40)],output:([a,t,g])=>[['Diffusion index (baseline 100)',a*g/40/t]],explanation:'Diffusion rate is proportional to area × gradient ÷ thickness when diffusion coefficient is fixed. Ventilation and perfusion help maintain the gas gradients.',challenge:'Halve area and double thickness. Explain why the index becomes one quarter of baseline.',note:'Fick-style relative comparison, not an anatomical scale drawing or a prediction of total oxygen delivery.'},
'renal-filtration':{params:[p('Filtration (mL/min)',60,150,125,5),p('Water reabsorbed (%)',95,99.8,99,.1)],output:([f,r])=>[['Filtered water (L/day)',f*1.44],['Returned to blood (L/day)',f*r/100*1.44],['Final fluid (L/day)',f*(1-r/100)*1.44]],explanation:'Final flow = filtered flow × fraction not reabsorbed. Convert mL/min to L/day by multiplying by 1.44. ADH can alter collecting-duct permeability; it does not filter blood directly.',challenge:'At 125 mL/min, change reabsorption from 99% to 98%. Why does final volume double?',note:'Water-balance arithmetic only. No solute transport, secretion, changing hormones or clinical assessment is simulated.'},
'pcr-amplification':{params:[p('Cycles',0,35,20),p('Starting target copies',1,100,1),p('Efficiency (%)',50,100,100)],output:([c,n,e])=>[['Expected target copies',n*(1+e/100)**c]],explanation:'N = N₀ × (1 + efficiency)ᶜ. At perfect efficiency each cycle doubles the target. The cycle separates strands, anneals primers and extends new DNA.',challenge:'Compare 80% and 100% efficiency after twenty cycles. Explain why a small per-cycle difference compounds.',note:'Ideal exponential phase. Real reactions plateau as reagents become limiting; this is not a laboratory-yield forecast.'},
'water-potential':{params:[p('Cell A solute potential (MPa)',-1.5,0,-.6,.1),p('Cell A pressure potential (MPa)',0,1,.2,.1),p('Cell B solute potential (MPa)',-1.5,0,-.4,.1),p('Cell B pressure potential (MPa)',0,1,0,.1)],output:([a,b,c,d])=>[['Cell A water potential (MPa)',a+b],['Cell B water potential (MPa)',c+d]],explanation:'Water potential = solute potential + pressure potential. Net movement is from higher to lower total water potential; higher may mean less negative.',challenge:'Can changing pressure reverse a prediction based only on solute concentration?',note:'Initial direction only. Gravity and matric terms are omitted; cell potentials would change as water moves.'}
};
function NumericModel({model,name}:{model:Model;name:string}){const[v,V]=useState(model.params.map(p=>p.start));const result=model.output(v);return <div className="activity-model"><div>{model.params.map((p,i)=><label className="activity-range" key={p.label}><span>{p.label}<strong>{v[i]}</strong></span><input type="range" min={p.min} max={p.max} step={p.step} value={v[i]} onChange={e=>V(v.map((n,j)=>j===i?+e.target.value:n))}/></label>)}<p>{model.challenge}</p></div><div aria-live="polite">{result.map(([label,n])=><div className="model-value" key={label}><span>{label}</span><strong>{Math.abs(n)>1e7?n.toExponential(2):n.toLocaleString('en',{maximumFractionDigits:2})}</strong></div>)}{name==='water-potential'&&<h3>{Math.abs(v[0]+v[1]-v[2]-v[3])<.001?'No net water movement':v[0]+v[1]>v[2]+v[3]?'Net movement: A → B':'Net movement: B → A'}</h3>}<p>{model.explanation}</p><p className="model-note">{model.note}</p></div></div>;}
function Memory(){const[second,S]=useState(false),[day,D]=useState(0);const curve=(x:number)=>second?(x<2?0:100*(1-Math.exp(-(x-2)/2))*Math.exp(-Math.max(0,x-10)/20)):(x<5?0:35*(1-Math.exp(-(x-5)/4))*Math.exp(-Math.max(0,x-14)/12));return <div className="activity-model"><div><label>Exposure<select value={String(second)} onChange={e=>S(e.target.value==='true')}><option value="false">First exposure</option><option value="true">Later exposure to the same antigen</option></select></label><label className="activity-range">Day {day}<input type="range" min={0} max={30} value={day} onChange={e=>D(+e.target.value)}/></label><p>Compare lag, peak and persistence. Antigen-specific memory can support a faster, stronger later response.</p></div><div><svg viewBox="0 0 420 260" className="activity-plot" role="img" aria-label={'Schematic antibody response, day '+day}><path d="M35 20V220H405" fill="none" stroke="currentColor"/><polyline points={Array.from({length:31},(_,i)=>(35+i*12)+','+(220-curve(i)*1.9)).join(' ')} fill="none" stroke="#25664b" strokeWidth="4"/><circle cx={35+day*12} cy={220-curve(day)*1.9} r="6" fill="#b64316"/><text x="40" y="18">Relative antibody response</text><text x="35" y="243">0</text><text x="350" y="243">30 days</text></svg><strong>{curve(day).toFixed(1)} response units</strong><p className="model-note">Invented teaching curves, not measured titres or a vaccination schedule. Responses vary with antigen, person and context.</p></div></div>;}
const bases=['U','C','A','G'],aa=['Phe','Phe','Leu','Leu','Ser','Ser','Ser','Ser','Tyr','Tyr','Stop','Stop','Cys','Cys','Stop','Trp','Leu','Leu','Leu','Leu','Pro','Pro','Pro','Pro','His','His','Gln','Gln','Arg','Arg','Arg','Arg','Ile','Ile','Ile','Met','Thr','Thr','Thr','Thr','Asn','Asn','Lys','Lys','Ser','Ser','Arg','Arg','Val','Val','Val','Val','Ala','Ala','Ala','Ala','Asp','Asp','Glu','Glu','Gly','Gly','Gly','Gly'];
const code=Object.fromEntries(bases.flatMap(a=>bases.flatMap(b=>bases.map(c=>a+b+c))).map((c,i)=>[c,aa[i]]));
function Code(){const[a,A]=useState('GAA'),[b,B]=useState('GAG');const x=code[a],y=code[b];return <div className="activity-model"><div>{[{label:'Original mRNA codon',v:a,set:A},{label:'Changed mRNA codon',v:b,set:B}].map(p=><label key={p.label}>{p.label} (5′ → 3′)<select value={p.v} onChange={e=>p.set(e.target.value)}>{Object.keys(code).map(c=><option key={c}>{c}</option>)}</select></label>)}<p>All 64 codons of the standard RNA code. RNA uses U rather than DNA’s T.</p></div><div><h2>{x} → {y}</h2><h3>{a===b?'No change':x==='Stop'&&y!=='Stop'?'Stop-loss change':y==='Stop'&&x!=='Stop'?'Nonsense change':x===y?'Synonymous change':'Missense change'}</h3><p>A substitution preserves sequence length. An insertion or deletion not divisible by three can cause a frameshift; this selector models substitutions only.</p><p className="model-note">Standard three-letter amino-acid abbreviations. Mitochondrial exceptions exist. A synonymous change need not be neutral; one codon alone cannot predict a whole protein’s function.</p></div></div>;}
const samples=['Starch solution','Glucose solution','Albumen solution','Vegetable oil','Mixed food extract','Distilled-water control'],present=[[1,0,0,0],[0,1,0,0],[0,0,1,0],[0,0,0,1],[1,1,1,0],[0,0,0,0]],tests=['Iodine','Benedict’s','Biuret','Ethanol emulsion'],yes=['Blue-black','Coloured precipitate','Lilac / purple','Milky-white emulsion'],no=['Yellow-brown','Remains blue','Remains blue','No milky emulsion'],methods=['Add iodine solution.','Add reagent and heat in a hot-water bath. Colour depends on reducing-sugar amount.','Add alkaline copper-containing Biuret reagent.','Shake with ethanol, then add extract to water. Keep flammable ethanol away from flames.'];
function Food(){const[s,S]=useState(0),[t,T]=useState(0),[guess,G]=useState('Positive'),[run,R]=useState(false);return <div className="activity-model"><div><label>Sample<select value={s} onChange={e=>{S(+e.target.value);R(false);}}>{samples.map((n,i)=><option key={n} value={i}>{n}</option>)}</select></label><label>Test<select value={t} onChange={e=>{T(+e.target.value);R(false);}}>{tests.map((n,i)=><option key={n} value={i}>{n}</option>)}</select></label><p>{methods[t]}</p><label>Your prediction<select value={guess} onChange={e=>{G(e.target.value);R(false);}}><option>Positive</option><option>Negative</option></select></label><button onClick={()=>R(true)}>Run the virtual test</button></div><div aria-live="polite">{run?<><h2>{present[s][t]?yes[t]:no[t]}</h2><p>{Boolean(present[s][t])===(guess==='Positive')?'Your prediction matches.':'Revise your prediction.'}</p></>:<p>Predict, then run the test.</p>}<p>Distilled water is a negative control; a known positive checks the method and reagent. Keep volumes and treatment comparable.</p><p className="model-note">Predefined sample composition. Real food extracts may mask colours or need preparation. Practical work requires supervision.</p></div></div>;}
export function AdditionalModel({name}:{name:string}){if(name==='immune-memory')return <Memory/>;if(name==='genetic-code')return <Code/>;if(name==='food-tests')return <Food/>;return models[name]?<NumericModel key={name} model={models[name]} name={name}/>:<p>Select an activity from the library.</p>;}
