export type CambridgeTopicGroup = "Foundations" | "Plant biology" | "Human systems" | "Continuity & environment";

export type CambridgeTopic = {
  slug: string;
  title: string;
  group: CambridgeTopicGroup;
  summary: string;
  focus: string[];
  examSkills: string[];
  mistakes: string[];
  practice: string[];
  relatedArticleSlug?: string;
};

export const cambridgeTopics: CambridgeTopic[] = [
  {
    slug: "cells",
    title: "Cells",
    group: "Foundations",
    summary: "Use cell structure to explain function, compare cell types and work confidently with microscopy and magnification.",
    focus: ["Animal, plant, bacterial and specialised cells", "Functions of cell structures", "Levels of organisation", "Magnification, image size and actual size"],
    examSkills: ["Compare cells using visible structural evidence", "Rearrange the magnification equation with correct units", "Link specialised features to a cell's function"],
    mistakes: ["Calling a cell wall a membrane", "Ignoring unit conversion in magnification", "Listing structures without explaining their purpose"],
    practice: ["Explain why a palisade cell contains many chloroplasts.", "Calculate actual size from an image and magnification.", "Compare a bacterial cell with a typical animal cell."],
    relatedArticleSlug: "cell-organelles-and-membrane-transport",
  },
  {
    slug: "classification",
    title: "Classification",
    group: "Foundations",
    summary: "Recognise shared characteristics, use classification keys and explain how DNA evidence can refine biological relationships.",
    focus: ["Species and the binomial system", "Major organism groups", "Viruses as acellular entities", "Dichotomous keys and evolutionary relationships"],
    examSkills: ["Apply a key to unfamiliar organisms", "Use observable features to justify classification", "Separate cellular organisms from viruses"],
    mistakes: ["Treating every microorganism as a bacterium", "Using habitat instead of biological characteristics", "Giving a common name when binomial nomenclature is required"],
    practice: ["Construct two steps of a dichotomous key.", "Explain why viruses are not placed in the five kingdoms.", "Use two features to distinguish an arthropod group."],
    relatedArticleSlug: "viruses-structure-classification-replication",
  },
  {
    slug: "movement-in-and-out-of-cells",
    title: "Movement into and out of cells",
    group: "Foundations",
    summary: "Explain diffusion, osmosis and active transport through gradients, membranes, energy use and surface-area relationships.",
    focus: ["Diffusion and net movement", "Osmosis through partially permeable membranes", "Active transport", "Effects of surface area, distance and gradients"],
    examSkills: ["Predict mass or length changes in osmosis experiments", "Distinguish observation from mechanism", "Explain adaptations for rapid exchange"],
    mistakes: ["Saying particles move only in one direction", "Describing solute movement as osmosis", "Forgetting that active transport requires energy"],
    practice: ["Predict the effect of concentrated solution on plant tissue.", "Explain why villi support rapid absorption.", "Compare diffusion with active transport."],
    relatedArticleSlug: "o-level-diffusion-osmosis-active-transport",
  },
  {
    slug: "biological-molecules",
    title: "Biological molecules",
    group: "Foundations",
    summary: "Connect carbohydrates, lipids and proteins with their building blocks, biological roles and standard food tests.",
    focus: ["Elements and subunits", "Starch, glycogen and cellulose", "Fats and proteins", "Benedict's, iodine, biuret and emulsion tests"],
    examSkills: ["State test reagents and positive results precisely", "Link molecular structure to biological use", "Interpret food-test data"],
    mistakes: ["Confusing the biuret and Benedict's tests", "Calling every carbohydrate sugar", "Forgetting to heat Benedict's reagent safely"],
    practice: ["Design a test for reducing sugar.", "Explain one role each of lipid and protein.", "Interpret a table of food-test results."],
    relatedArticleSlug: "biological-molecules-structure-and-function",
  },
  {
    slug: "enzymes",
    title: "Enzymes",
    group: "Foundations",
    summary: "Explain enzyme specificity and interpret how temperature, pH and concentration affect reaction rate.",
    focus: ["Active sites and specificity", "Temperature and kinetic energy", "pH and enzyme shape", "Rate investigations and controls"],
    examSkills: ["Describe and explain rate graphs", "Plan a fair enzyme investigation", "Use collision and denaturation language accurately"],
    mistakes: ["Saying enzymes are killed", "Treating optimum as the same for every enzyme", "Describing a graph without explaining the change"],
    practice: ["Explain the shape of a temperature-rate curve.", "Identify controls in an amylase experiment.", "Predict the effect of extreme pH on an active site."],
    relatedArticleSlug: "enzymes-activation-energy-and-inhibition",
  },
  {
    slug: "plant-nutrition",
    title: "Plant nutrition",
    group: "Plant biology",
    summary: "Relate leaf structure, limiting factors and mineral requirements to photosynthesis and plant growth.",
    focus: ["Photosynthesis equation", "Leaf adaptations", "Limiting factors", "Nitrate and magnesium ions"],
    examSkills: ["Interpret limiting-factor graphs", "Explain leaf adaptations as cause-and-effect links", "Plan starch-testing investigations"],
    mistakes: ["Saying plants obtain food from soil", "Confusing respiration with photosynthesis", "Listing stomata without explaining gas movement"],
    practice: ["Explain two adaptations of a palisade layer.", "Interpret a light-intensity graph.", "Describe a test showing light is needed for photosynthesis."],
  },
  {
    slug: "transport-in-flowering-plants",
    title: "Transport in flowering plants",
    group: "Plant biology",
    summary: "Trace water, mineral ions and assimilates through roots, xylem, leaves and phloem.",
    focus: ["Root-hair absorption", "Xylem structure and transpiration", "Stomatal control", "Translocation in phloem"],
    examSkills: ["Explain environmental effects on transpiration", "Link vessel structure to transport", "Interpret potometer results cautiously"],
    mistakes: ["Saying a potometer directly measures transpiration", "Confusing xylem with phloem", "Assuming translocation is always upward"],
    practice: ["Explain why wind increases water uptake.", "Compare xylem and phloem.", "Evaluate one limitation of a potometer."],
  },
  {
    slug: "plant-coordination-and-response",
    title: "Coordination and response in plants",
    group: "Plant biology",
    summary: "Explain directional growth responses and how auxin distribution produces different root and shoot responses.",
    focus: ["Phototropism", "Gravitropism", "Auxin in shoots and roots", "Adaptive value of growth responses"],
    examSkills: ["Predict growth direction from a stimulus", "Explain unequal growth using auxin", "Interpret controlled seedling experiments"],
    mistakes: ["Calling a tropism movement from one place to another", "Assuming auxin has the same effect in roots and shoots", "Ignoring the direction of the stimulus"],
    practice: ["Predict a shoot response to one-sided light.", "Explain positive gravitropism in roots.", "Design a control for a tropism investigation."],
  },
  {
    slug: "human-nutrition",
    title: "Human nutrition",
    group: "Human systems",
    summary: "Connect diet, digestion, absorption and assimilation across the alimentary canal.",
    focus: ["Balanced diet and deficiency", "Mechanical and chemical digestion", "Digestive enzymes", "Villus adaptations and assimilation"],
    examSkills: ["Trace a nutrient from food to cells", "Match enzymes with substrates and products", "Explain villus adaptations"],
    mistakes: ["Confusing absorption with assimilation", "Placing bile as an enzyme", "Saying digestion occurs only in the stomach"],
    practice: ["Explain how bile supports fat digestion.", "Trace starch digestion to absorption.", "Relate villus structure to function."],
    relatedArticleSlug: "digestion-and-absorption",
  },
  {
    slug: "human-gas-exchange",
    title: "Human gas exchange",
    group: "Human systems",
    summary: "Use pressure, muscle action and diffusion to explain ventilation and exchange at the alveoli.",
    focus: ["Airway structure", "Ventilation mechanics", "Alveolar exchange", "Effects of exercise and smoking"],
    examSkills: ["Compare inhalation with exhalation", "Explain alveolar adaptations", "Interpret breathing-rate or volume data"],
    mistakes: ["Confusing ventilation with respiration", "Reversing diaphragm movement", "Saying oxygen is pumped into blood"],
    practice: ["Explain inhalation using pressure changes.", "Describe three alveolar adaptations.", "Interpret breathing data before and after exercise."],
  },
  {
    slug: "respiration",
    title: "Respiration",
    group: "Human systems",
    summary: "Distinguish aerobic and anaerobic respiration and explain why cells require controlled energy release.",
    focus: ["Aerobic respiration", "Anaerobic respiration", "Energy uses in cells", "Oxygen debt and exercise"],
    examSkills: ["Write balanced word equations", "Compare yields without unsupported numbers", "Explain exercise-related changes"],
    mistakes: ["Calling respiration breathing", "Saying energy is created", "Using the plant anaerobic products for muscle cells"],
    practice: ["Compare aerobic and anaerobic respiration.", "Explain why breathing remains fast after exercise.", "State three cellular uses of energy."],
    relatedArticleSlug: "cellular-respiration-atp-production",
  },
  {
    slug: "transport-in-humans",
    title: "Transport in humans",
    group: "Human systems",
    summary: "Explain double circulation, heart action, vessel adaptations, blood components and coronary disease.",
    focus: ["Heart structure and cardiac cycle", "Arteries, veins and capillaries", "Blood components", "Coronary heart disease"],
    examSkills: ["Trace blood through the heart", "Compare vessels using structure and function", "Interpret heart-rate and circulation data"],
    mistakes: ["Confusing pulmonary artery and vein contents", "Saying valves actively pump blood", "Listing vessel features without linking them to pressure"],
    practice: ["Trace blood from vena cava to aorta.", "Explain why capillaries are one cell thick.", "Compare artery and vein structure."],
    relatedArticleSlug: "cardiac-cycle-and-circulation",
  },
  {
    slug: "disease-and-immunity",
    title: "Disease and immunity",
    group: "Human systems",
    summary: "Connect pathogen transmission, body defences, antibodies, vaccination and public-health control.",
    focus: ["Pathogens and transmission", "Physical and chemical barriers", "Antibodies and lymphocytes", "Vaccination and community protection"],
    examSkills: ["Suggest transmission controls from evidence", "Explain vaccination as a sequence", "Distinguish antibiotics from antibodies"],
    mistakes: ["Using antibiotics for viral disease", "Saying vaccines directly kill pathogens", "Confusing an antigen with an antibody"],
    practice: ["Explain how vaccination creates protection.", "Suggest controls for a water-borne pathogen.", "Compare antibody and antigen."],
    relatedArticleSlug: "innate-vs-adaptive-immunity",
  },
  {
    slug: "excretion",
    title: "Excretion",
    group: "Human systems",
    summary: "Explain removal of metabolic waste, kidney function and regulation of water concentration.",
    focus: ["Definition of excretion", "Urea formation", "Kidney and nephron function", "Water balance and ADH"],
    examSkills: ["Distinguish excretion from egestion", "Trace filtrate through a nephron", "Explain ADH responses using feedback"],
    mistakes: ["Calling faeces an excretory product", "Saying all filtered glucose is excreted", "Reversing ADH effects on water reabsorption"],
    practice: ["Explain why urea must be removed.", "Describe selective reabsorption.", "Predict ADH change after heavy sweating."],
    relatedArticleSlug: "negative-feedback-made-simple",
  },
  {
    slug: "coordination-and-control",
    title: "Coordination and control",
    group: "Human systems",
    summary: "Compare nervous and hormonal coordination and explain receptors, reflexes and homeostatic control.",
    focus: ["Receptors and effectors", "Neurones and reflex arcs", "Hormones", "Blood-glucose and temperature control"],
    examSkills: ["Trace a reflex pathway", "Compare nervous and endocrine responses", "Explain negative feedback clearly"],
    mistakes: ["Confusing receptor with sense organ", "Treating hormones as electrical impulses", "Describing feedback without the corrective response"],
    practice: ["Trace a reflex from stimulus to response.", "Compare insulin and glucagon action.", "Explain one response to rising body temperature."],
    relatedArticleSlug: "nerve-impulse-and-synapse",
  },
  {
    slug: "development-and-continuity-of-life",
    title: "Development and continuity of life",
    group: "Continuity & environment",
    summary: "Connect sexual and asexual reproduction with gametes, fertilisation, development and plant reproduction.",
    focus: ["Asexual and sexual reproduction", "Flower structure and pollination", "Human reproductive systems", "Fertilisation and development"],
    examSkills: ["Compare reproductive strategies", "Trace pollen to seed formation", "Interpret menstrual-cycle hormone data"],
    mistakes: ["Confusing pollination with fertilisation", "Saying sexual reproduction always produces more offspring", "Reversing FSH, LH, oestrogen and progesterone roles"],
    practice: ["Compare sexual and asexual reproduction.", "Explain how a seed forms after pollination.", "Interpret a menstrual-cycle graph."],
    relatedArticleSlug: "human-reproduction-and-hormonal-control",
  },
  {
    slug: "inheritance",
    title: "Inheritance",
    group: "Continuity & environment",
    summary: "Move from chromosomes and genes to crosses, variation, selection and modern genetic interpretation.",
    focus: ["DNA, genes and chromosomes", "Mitosis and meiosis", "Monohybrid inheritance", "Variation and selection"],
    examSkills: ["Construct genetic diagrams", "Use genotype and phenotype notation", "Interpret pedigrees and variation data"],
    mistakes: ["Writing allele symbols inconsistently", "Confusing gene with allele", "Giving ratios without showing a genetic cross"],
    practice: ["Complete a heterozygous monohybrid cross.", "Explain how meiosis produces variation.", "Interpret a simple pedigree."],
    relatedArticleSlug: "mendelian-inheritance-and-crosses",
  },
  {
    slug: "biotechnology-and-genetic-modification",
    title: "Biotechnology and genetic modification",
    group: "Continuity & environment",
    summary: "Explain how microorganisms, enzymes and gene transfer are used to make useful biological products.",
    focus: ["Fermentation", "Industrial enzyme use", "Genetic modification", "Benefits and risks of biotechnology"],
    examSkills: ["Describe a genetic-modification sequence", "Evaluate benefits and risks", "Interpret fermentation conditions"],
    mistakes: ["Saying bacteria consciously make products", "Leaving out vector or host steps", "Presenting an opinion without biological evidence"],
    practice: ["Outline production of human insulin by bacteria.", "Explain why fermenters are kept sterile.", "Evaluate one GM crop using balanced evidence."],
    relatedArticleSlug: "biotechnology-vaccines-diagnosis-gene-therapy",
  },
  {
    slug: "organisms-and-environment",
    title: "Relationships of organisms with one another and with the environment",
    group: "Continuity & environment",
    summary: "Use food webs, nutrient cycles, population data and human impacts to explain ecosystem change.",
    focus: ["Energy flow and food webs", "Carbon and water cycles", "Population change", "Conservation and human impact"],
    examSkills: ["Interpret pyramids and population graphs", "Predict food-web consequences", "Evaluate conservation decisions"],
    mistakes: ["Showing energy cycling instead of flowing", "Confusing a habitat with an ecosystem", "Claiming one correlation proves a cause"],
    practice: ["Predict the effect of removing one consumer.", "Explain why energy decreases along a food chain.", "Evaluate a conservation strategy from supplied data."],
    relatedArticleSlug: "evolution-lamarck-darwin-natural-selection",
  },
];

export const cambridgeTopicGroups: Array<"All topics" | CambridgeTopicGroup> = ["All topics", "Foundations", "Plant biology", "Human systems", "Continuity & environment"];

export function getCambridgeTopic(slug: string) {
  return cambridgeTopics.find((topic) => topic.slug === slug);
}
