import {notFound} from 'next/navigation';
import Link from 'next/link';
import {learningChapters} from '../catalogue';
import {Header,Footer,ConceptDiagram} from '../../components';
import {StudyControls} from '../../study-controls';
import {links,videos} from '../../content';
import {PackChecklist} from '../pack-tools';
export function generateStaticParams(){return learningChapters.map(c=>({slug:c.slug}));}
export async function generateMetadata({params}:{params:Promise<{slug:string}>}){const{slug}=await params,c=learningChapters.find(c=>c.slug===slug);return{title:c?.title+' Chapter Pack',description:'Connected lesson, notes, activities, concept diagrams, practice and printable revision for '+c?.title,alternates:{canonical:'/learn/'+slug}};}
export default async function Page({params}:{params:Promise<{slug:string}>}){const{slug}=await params,c=learningChapters.find(c=>c.slug===slug);if(!c||!c.article)notFound();const video=videos.find(v=>v.chapter===c.title),diagram=c.article.sections.find(s=>s.diagram)?.diagram;return <><Header/><main id="main-content" className="wrap feature-page"><Link className="chapter-back" href="/learn">← All chapter packs</Link><header className="learning-heading"><p className="eyebrow">MDCAT · CHAPTER {c.index}</p><h1>{c.title}</h1><p>{c.article.description}</p><div className="pack-hero-actions"><Link className="button button-dark" href={'/learn/'+slug+'/revision'}>Open printable revision sheet ↗</Link><Link href={'/practice?chapter='+encodeURIComponent(c.title)}>Start chapter practice →</Link></div></header><StudyControls id={'/learn/'+slug} title={c.title} notes/><PackChecklist slug={slug}/><nav className="pack-jumps" aria-label="Chapter pack sections">{['lesson','notes','activity','diagram','quiz','revision'].map((s,i)=><a key={s} href={'#pack-'+s}>{String(i+1).padStart(2,'0')} {s}</a>)}</nav><div className="connected-pack">
<section id="pack-lesson"><p className="eyebrow">01 / LESSON</p><h2>Build the explanation.</h2><ul>{c.article.objectives.map(o=><li key={o}>{o}</li>)}</ul><div className="pack-links"><Link href={'/articles/'+c.guide}>Read the complete chapter lesson ↗</Link><a href={video?.href??links.playlist} target="_blank" rel="noreferrer">{video?'Watch: '+video.title:'Browse the teaching playlist'} ↗</a></div>{!video&&<small>A chapter-specific video has not been linked yet; the button opens the full teaching playlist.</small>}</section>
<section id="pack-notes"><p className="eyebrow">02 / NOTES</p><h2>The essentials, in one place.</h2><ul>{c.article.recap.map(r=><li key={r}>{r}</li>)}</ul><div className="pack-links"><a href={links.studentDrive} target="_blank" rel="noreferrer">Open the lecture-notes folder ↗</a><Link href={'/articles/'+c.guide}>Read the detailed notes on this site ↗</Link></div><small>The Drive link opens the shared folder. Look for {c.title}; it is not a direct file download.</small></section>
<section id="pack-activity"><p className="eyebrow">03 / ACTIVITY</p><h2>Test the idea by changing something.</h2><p>Predict the result first, run the activity, then explain what changed and why.</p><div className="chapter-activity-list">{c.activities.map(a=><Link href={'/lab/'+a.slug} key={a.slug}>{a.title}<small>{a.kind} ↗</small></Link>)}</div></section>
<section id="pack-diagram"><p className="eyebrow">04 / DIAGRAM</p><h2>Make the connections visible.</h2>{diagram&&<ConceptDiagram diagram={diagram}/>}<p>Cover the labels, redraw the sequence or comparison, and explain each connection aloud.</p><Link href={'/articles/'+c.guide}>See diagrams in the full explanation ↗</Link></section>
<section id="pack-quiz"><p className="eyebrow">05 / QUIZ</p><h2>Retrieve before you reread.</h2><p>Build a timed test from this chapter’s 100 practice questions. Questions and options are shuffled; missed answers feed your revision notebook.</p><div className="pack-links"><Link href={'/practice?chapter='+encodeURIComponent(c.title)}>Take the chapter test ↗</Link><Link href="/revision">Review saved mistakes ↗</Link><a href={'/question-banks/'+slug+'.json'} download>Download the question bank (JSON) ↓</a></div><small>Original practice items, including related concept variants; not official examination questions.</small></section>
<section id="pack-revision"><p className="eyebrow">06 / REVISION SHEET</p><h2>Take the chapter away with you.</h2><p>A print-friendly sheet brings together the learning targets, key points, concept diagram, written recall prompts and applied MCQs. Add the answer key when you are ready to check.</p><Link className="button button-dark" href={'/learn/'+slug+'/revision'}>Print / save the chapter sheet ↗</Link><p><Link href="/account">Back up your checklist and study notes ↗</Link></p></section>
</div></main><Footer/></>;}
