export type PracticalTask={id:string;title:string;prompt:string;kind:'number'|'choice'|'written';unit?:string;answer?:number;tolerance?:number;options?:string[];correct?:number;model:string;points?:string[];topic:string};
export const practicalTasks:PracticalTask[]=[
{id:'magnification',title:'Convert before calculating',topic:'Cells',kind:'number',prompt:'A cell is 50 μm long. Its drawing is 30 mm long. Calculate the magnification (enter the number after ×).',unit:'× magnification',answer:600,tolerance:0,model:'30 mm = 30,000 μm. Magnification = image size ÷ actual size = 30,000 ÷ 50 = ×600. Magnification is a ratio and has no unit.'},
{id:'mass-change',title:'Osmosis: signed percentage change',topic:'Movement into and out of cells',kind:'number',prompt:'A potato cylinder changes from 5.00 g to 4.40 g. Calculate its percentage change in mass, including the sign.',unit:'%',answer:-12,tolerance:.01,model:'(4.40 − 5.00) ÷ 5.00 × 100 = −12%. The negative sign shows mass loss. Use initial mass as the denominator.'},
{id:'mean',title:'Calculate a mean',topic:'Handling data',kind:'number',prompt:'Three repeat reaction times are 42 s, 45 s and 48 s. Calculate the mean reaction time.',unit:'s',answer:45,tolerance:0,model:'(42 + 45 + 48) ÷ 3 = 45 s. Repeats help estimate typical performance; more repeats do not by themselves remove a systematic error.'},
{id:'rate',title:'Calculate a production rate',topic:'Plant nutrition',kind:'number',prompt:'An aquatic plant produces 12.0 cm³ of gas in 5.0 minutes. Calculate the mean gas-production rate.',unit:'cm³/min',answer:2.4,tolerance:.01,model:'Rate = volume ÷ time = 12.0 ÷ 5.0 = 2.4 cm³/min. Gas volume is generally more informative than bubble counts because bubbles may differ in size.'},
{id:'variables',title:'Identify the dependent variable',topic:'Enzymes',kind:'choice',prompt:'A student changes pH while holding temperature, enzyme concentration and substrate concentration constant. They measure the time for starch to disappear. Which is the dependent variable?',options:['pH','Time for starch to disappear','Enzyme concentration','Temperature'],correct:1,model:'The dependent variable is the measured outcome: time for starch to disappear. pH is the independent variable; temperature and concentrations are controlled.'},
{id:'errors',title:'Separate bias from random variation',topic:'Evaluation',kind:'choice',prompt:'A balance reads +0.20 g when empty and is not zeroed. Which improvement directly addresses this error?',options:['Take more repeats without zeroing','Use fewer samples','Zero or calibrate the balance before measurement','Round every mass to a whole number'],correct:2,model:'A zero error biases measurements. Zeroing or calibration addresses its cause; averaging repeated biased readings does not remove the offset.'},
{id:'sampling',title:'Estimate a population',topic:'Ecology',kind:'number',prompt:'Five randomly placed 0.25 m² quadrats contain 6, 8, 5, 7 and 9 plants. Estimate the number in a uniform 100 m² area.',unit:'plants',answer:2800,tolerance:0,model:'Mean count = 35 ÷ 5 = 7 plants per quadrat. Density = 7 ÷ 0.25 = 28 plants/m². Estimate = 28 × 100 = 2,800 plants. This estimate assumes the random sample represents the area.'},
{id:'plan-osmosis',title:'Plan a fair osmosis investigation',topic:'Investigation planning',kind:'written',prompt:'Plan how you would investigate the effect of sucrose concentration on the percentage mass change of potato cylinders. Include measurement, controls, repeats and one safety precaution.',model:'Prepare a range of measured sucrose concentrations. Cut cylinders from the same potato with equal dimensions. Record each initial mass, immerse for equal times in equal solution volumes at the same temperature, blot consistently and reweigh. Calculate percentage mass change using each initial mass. Use at least three cylinders per concentration, calculate means and plot concentration against mean percentage change. Handle the cutting tool carefully on a suitable surface under supervision.',points:['A measured range of sucrose concentrations','Initial and final mass, with consistent blotting','Equal dimensions, temperature, immersion time and solution volume','Repeats for each concentration and a mean','Percentage change using initial mass; appropriate graph','A specific cutting-tool safety precaution']}
];
export type DiagramKind='neuron'|'nephron'|'cell'|'alveolus';
export const diagrams:{id:DiagramKind;title:string;labels:string[];tip:string;href:string}[]=[
{id:'neuron',title:'A myelinated motor neuron',labels:['Dendrites','Cell body','Nucleus','Myelin sheath','Node of Ranvier','Axon terminals'],tip:'Dendrites receive input; the axon carries impulses towards the terminals. Myelin insulates the axon, with gaps at nodes.',href:'/articles/nerve-impulse-and-synapse'},
{id:'nephron',title:'The route through a nephron',labels:['Glomerulus','Bowman’s capsule','Proximal convoluted tubule','Loop of Henle','Distal convoluted tubule','Collecting duct'],tip:'Blood remains inside glomerular capillaries. Filtrate enters the capsule space and then the tubule; they are different fluid compartments.',href:'/articles/negative-feedback-made-simple'},
{id:'cell',title:'A simplified plant cell',labels:['Cell wall','Cell membrane','Cytoplasm','Nucleus','Chloroplast','Vacuole'],tip:'The cellulose wall lies outside the membrane. A mature plant cell often has a large central vacuole; chloroplasts occur in photosynthetic cells.',href:'/articles/cell-organelles-and-membrane-transport'},
{id:'alveolus',title:'An alveolus and its capillary',labels:['Alveolar air space','Alveolar epithelium','Capillary wall','Red blood cell','Oxygen into blood','Carbon dioxide into alveolus'],tip:'Oxygen diffuses from alveolar air towards blood; carbon dioxide diffuses the opposite way. Both move down partial-pressure gradients.',href:'/articles/breathing-gas-exchange-and-transport'}
];
export const pathways=[
{id:'blood',title:'Blood from the body to the body',nodes:['Venae cavae','Right atrium','Right ventricle','Pulmonary artery','Lung capillaries','Pulmonary veins','Left atrium','Left ventricle','Aorta'],explanation:'The pulmonary circuit carries blood through the lungs before the left ventricle pumps it into systemic circulation. Valves are omitted in this simplified route.'},
{id:'air',title:'Inspired air to the gas-exchange surface',nodes:['Nasal cavity','Pharynx','Larynx','Trachea','Bronchus','Bronchiole','Alveolus'],explanation:'Conducting airways deliver air; the thin alveolar surface supports gas exchange.'},
{id:'urine',title:'Fluid from capsule to outside the body',nodes:['Bowman’s capsule space','Proximal tubule','Loop of Henle','Distal tubule','Collecting duct','Renal pelvis','Ureter','Bladder','Urethra'],explanation:'Filtrate is modified by reabsorption and secretion in the nephron and collecting duct. Urine then drains towards the bladder and exits through the urethra.'},
{id:'reflex',title:'A withdrawal reflex',nodes:['Skin receptor','Sensory neuron','Relay neuron in spinal cord','Motor neuron','Skeletal muscle effector'],explanation:'The spinal circuit can initiate withdrawal before conscious awareness. Information is also relayed to the brain.'}
];
