import Link from 'next/link';
import {notFound} from 'next/navigation';
import {learningChapters} from '../../catalogue';
import {Header,Footer,ConceptDiagram} from '../../../components';
import {PrintPack} from '../../pack-tools';
import {quizQuestions} from '../../../practice/questions';
import {QuestionVisual} from '../../../practice/question-tools';
export function generateStaticParams(){return learningChapters.map(c=>({slug:c.slug}));}
export async function generateMetadata({params}:{params:Promise<{slug:string}>}){const{slug}=await params,c=learningChapters.find(c=>c.slug===slug);return{title:c?.title+' Printable Revision Sheet',alternates:{canonical:'/learn/'+slug+'/revision'}};}
export default async function Page({params}:{params:Promise<{slug:string}>}){const{slug}=await params,c=learningChapters.find(c=>c.slug===slug);if(!c?.article)notFound();const a=c.article,diagram=a.sections.find(s=>s.diagram)?.diagram,qs=quizQuestions.filter(q=>q.chapter===c.title&&q.id.startsWith('applied-')).slice(0,3);return <><Header/><main className="wrap feature-page chapter-sheet" id="main-content"><Link className="chapter-back" href={'/learn/'+slug}>← Back to the connected pack</Link><header className="sheet-heading"><p className="eyebrow">BIOLOGY WITH HAMZA · MDCAT REVISION</p><h1>{c.title}</h1><p>Name: ____________________ &nbsp; Date: ______________</p><p>Recall first. Check second. Return to the ideas you missed.</p></header><PrintPack/><section><h2>Learning targets</h2><ul>{a.objectives.map(x=><li key={x}>{x}</li>)}</ul><h2>Core notes</h2><ul>{a.recap.map(x=><li key={x}>{x}</li>)}</ul></section>{diagram&&<section><h2>Read, cover and redraw</h2><ConceptDiagram diagram={diagram}/></section>}<section><h2>Written recall</h2>{a.checks.map((q,i)=><div className="sheet-question" key={q.question}><h3>{i+1}. {q.question}</h3><div className="answer-lines" aria-label="Space to write your answer"/></div>)}</section><section><h2>Apply the idea</h2>{qs.map((q,i)=><div className="sheet-question" key={q.id}><h3>{i+1}. {q.stem}</h3><QuestionVisual question={q}/><ol type="A">{q.options.map(o=><li key={o}>{o}</li>)}</ol><p>My answer: _____ &nbsp; Reason: ____________________________________</p></div>)}</section><section className="sheet-answer-key"><h2>Answer key</h2><p>Cover this section while attempting the questions.</p><h3>Written recall</h3>{a.checks.map((q,i)=><p key={q.question}><strong>{i+1}.</strong> {q.answer}</p>)}<h3>Applied questions</h3>{qs.map((q,i)=><p key={q.id}><strong>{i+1}. {String.fromCharCode(65+q.answer)}</strong> — {q.explanation}</p>)}</section><footer className="sheet-footer"><p>Continue: hamzaramzan.online/learn/{slug}/</p><p>Independent learning material; not an official examination paper. For full explanations, diagrams and sources, use the chapter lesson.</p></footer></main><Footer/></>;}
